### ISSUE TITLE
Email Templates Modal

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#10]
This will be a part of email templates

This modal will show up anywhere in the application where an email needs to be sent.  Look at LSF's email handler and template handler using CKEditor.

See Email Management Wireframe: https://balsamiq-wireframes.appspot.com/?state=%7B%22ids%22:%5B%221C2D4xPhWindiXlz6WTfgXFVENu5_OwiX%22%5D,%22action%22:%22open%22,%22userId%22:%22109665407847548855125%22,%22resourceKeys%22:%7B%7D%7D

The slides titled "Email Templates modal" and "Email Templates modal selected template" are what we want this page to look like.
![image](https://user-images.githubusercontent.com/28715731/121894308-fe8e0300-ccec-11eb-9db1-7d5c69c27f78.png)
![image](https://user-images.githubusercontent.com/28715731/121894367-0e0d4c00-cced-11eb-9025-8847fc28e6ee.png)

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #10: Email Templates Modal](https://trello.com/c/zEwvdjV3/275-celts-10-email-templates-modal)

**Comment by zachneill** [comment]
This is being taken care of in issue #99 and PR #133

**Comment by Boorclark** [comment]
PR #133  has been merged. Closing issue.
