### ISSUE TITLE
Fix the search button on `Student Search`

### ISSUE THREAD

**Issue by azabeli** [BCStudentSoftwareDevTeam/celts#1016]
The magnifying glass of the Search button doesn't work(it is not clickable) and nothing pops up until the user hits enter. It should be clickable and pop relevant information to what the user is searching for, without necessarily waiting for the user to hit enter.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor the code for Student Search Page #1016](https://trello.com/c/bAVjVtIW/672-refactor-the-code-for-student-search-page-1016)

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix the search button on Student Search #1016](https://trello.com/c/bAVjVtIW/672-fix-the-search-button-on-student-search-1016)
