### ISSUE TITLE
Attendance Limit for RSVP is allowed to be negative

### ISSUE THREAD

**Issue by andersoncedu** [BCStudentSoftwareDevTeam/celts#1017]
On the view/edit event page when creating or editing an event, the attendance limit is allowed to be negative. The value should probably be locked to 1 at the lowest as there should never be 0 or negative for the attendance limit when rsvp is required.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Attendance Limit for RSVP is allowed to be negative #1017](https://trello.com/c/llv39CYy/671-attendance-limit-for-rsvp-is-allowed-to-be-negative-1017)
