### ISSUE TITLE
Make Remove Button functional on New Proposal For Service-Learning Course Page

### ISSUE THREAD

**Issue by azabeli** [BCStudentSoftwareDevTeam/celts#1019]
On the New Proposal For Service-Learning Course Page when a course instructor is added to a new course Proposal, they can't be removed because the "Remove" button isn't functional. This needs to be changed and make the remove button functional.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make Remove Button functional on New Proposal For Service-Learning Course Page #1019](https://trello.com/c/UBI3Y7aS/670-make-remove-button-functional-on-new-proposal-for-service-learning-course-page-1019)
