### ISSUE TITLE
Change flash message when a banned student is scanned in through kiosk entry. 

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#1045]
Currently, if a user has their ID scanned for a Kiosk sign in at an event in a program they are banned from we give no indication on the Kiosk page to the people who are doing the scanning. We should instead show a red flash message saying something like  "Sign-in failed, please talk with an Admin."

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change Banned indicator when a student is scanned in through kiosk entry. #1045](https://trello.com/c/T16Y4b0E/683-change-banned-indicator-when-a-student-is-scanned-in-through-kiosk-entry-1045)

**Comment by njounkengdaizem** [comment]
I am working on this issue
