### ISSUE TITLE
Fix `View Past Events` toggle

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#1047]
Currently, we have a check at the bottom of `event_list.html` to which sets the past events toggle, we should change the check to compare against the new `termOrder` instead of `g.current_term`.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix View Past Events toggle #1047](https://trello.com/c/rCkgCuWw/688-fix-view-past-events-toggle-1047)

**Comment by Mercy-Eze** [comment]
Issue resolved on #1069
