### ISSUE TITLE
Create course participants UI 

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#1059]

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create course participants UI #1059](https://trello.com/c/ujuECWK6/696-create-course-participants-ui-1059)

**Comment by BrianRamsay** [comment]
We have added the functionality to submit course participants and import courses for the registrar but there is no way to access that information outside of the database.

We need to:
- See the imported courses and renew or edit (likely with the same kind of view we use for in-progress and approved courses)
- See the course participants attached to a course
- Set the hours that a course gives the participants
- Make sure that everything shows up in the Service Transcript nicely

**Comment by hoerstl** [comment]
We also need to add the ability to alter any information that is necessary for renewing a course as usual:
![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/89316750/7e592f5f-34d6-4afe-b1db-2311a7cec37e)
![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/89316750/f24ad34d-0c59-4a49-8af6-1174f1763c85)

**Comment by bledsoef** [comment]
Closed in PR #1111
