### ISSUE TITLE
Fix the logic for the student search button on the student search page

### ISSUE THREAD

**Issue by Karina-Agliullova** [BCStudentSoftwareDevTeam/celts#1075]
If we search for a student that exists in a database, and we hit enter or the search icon after typing their name, the error occurs saying that the user doesn't exist, which is wrong because it shows that that student exists in the dropdown when we type their name

**Comment by bledsoef** [comment]
Is this currently being worked on/has any progress been made on this @Karina-Agliullova?

**Comment by bledsoef** [comment]
Closed in #1074
