### ISSUE TITLE
Add `Sustained Engagement` functionality  

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#1094]
Controllers: 
`/cceMinor/<username>/identifyCommunityEngagement/<term>`, `/cceMinor/<username>/addCommunityEngagement`, and `/cceMinor/<username>/removeCommunityEngagement`

Balsamiq: https://drive.google.com/file/d/1X8v6z63RKa56WTyIyNLx3LX_kaz7l6Pr/view?usp=share_link

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Sustained Engagement functionality #1094](https://trello.com/c/frsynpgZ/707-add-sustained-engagement-functionality-1094)

**Comment by bledsoef** [comment]
I believe this was closed in #1106
