### ISSUE TITLE
Make the sidebar Activity Logs consistent with the page title Admin Logs

### ISSUE THREAD

**Issue by bledsoef** [BCStudentSoftwareDevTeam/celts#1120]
**Very low priority issue, let's save this for this summer's cohort.**

On the sidebar when you are logged in as an admin, the sidebar has a page called "Activity Logs". However, when we go to that page the title is "Admin Logs". The title of the page and the route are also "Admin Logs". It would be a good idea to make these consistent, likely by changing the name of the sidebar link to be Admin Logs.

![Screenshot_20240202_123928](https://github.com/BCStudentSoftwareDevTeam/celts/assets/89262886/2de4ff49-a4d6-4af1-af40-0d6a308f126f)

**Comment by Mahak1729** [comment]
After finally being able to pick an actual issue today, we decided to change Admin Logs to Activity Logs for better consistency & logic. 

While we were able to make the initial changes successfully, we are currently working on making the changes in routing / URL. We have mass-changed/refactored all the varibales to activityLogs, but it does not seem to do the trick now.

**Comment by bledsoef** [comment]
Closed in #1217
