### ISSUE TITLE
Kiosk mode is a little bit clunky when making it full screen

### ISSUE THREAD

**Issue by bledsoef** [BCStudentSoftwareDevTeam/celts#1122]
If you go to the Kiosk Entry page for Manage Volunteers and toggle full screen, the text box will no longer be centered. Then, when you toggle out of full screen with the Esc key the sidebar does not show up. Let's make this process a little bit cleaner.

Also lets make sure that the B number input box is always focused.

![Screenshot_20240202_134603](https://github.com/BCStudentSoftwareDevTeam/celts/assets/89262886/aec6c3c5-f1db-4039-b969-405cebaa1aef)
![Screenshot_20240202_134555](https://github.com/BCStudentSoftwareDevTeam/celts/assets/89262886/79b297f0-54ad-4e8a-a93b-4c77dc64fd7d)

**Comment by bledsoef** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Kiosk mode is a little bit clunky when making it full screen](https://trello.com/c/9kB9X8M7/723-kiosk-mode-is-a-little-bit-clunky-when-making-it-full-screen)

**Comment by MImran2002** [comment]
We have done the event kiosk with hiding the sidebar and footer on multiple screen width and call the full screen only on the input show class in html. And we replace the toggle and untoggle with a button that changes if we close and open full screen.

**Comment by bledsoef** [comment]
Closed in issue #1256
