### ISSUE TITLE
Add full name to emergency contact updates in Admin Logs

### ISSUE THREAD

**Issue by BrianRamsay** [BCStudentSoftwareDevTeam/celts#1124]
The admin log entry for emergency contact updates includes usernames twice. Each of those should be the user in question's full name rather than username.

**Comment by bledsoef** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add full name to emergency contact updates in Admin Logs](https://trello.com/c/YG4WspcT/721-add-full-name-to-emergency-contact-updates-in-admin-logs)

**Comment by bledsoef** [comment]
Closed in #1285
