### ISSUE TITLE
Add docstrings and comments if necessary to files in the events logic file

### ISSUE THREAD

**Issue by bledsoef** [BCStudentSoftwareDevTeam/celts#1132]
**This is a low priority issue lets save this for the summer cohort**

There are a few instances in the `app/logic/events.py` file where we have functions without docstings, without **good** docstrings, or without **good** comments. 

Reference [the documentation](http://ssdt-documentation.berea.edu/ssdt-program/documenting-your-code) for how to properly document code.

### Places with poor code documentation:
- `cancelEvent` (poor docstring)
- `deleteEventAndAllFollowing` and `deleteAllRecurringEvents` (no comments, could be a little bit confusing)
- `saveEventToDb` (no docstring, very few comments)
- `getStudentLedEvents` (no docstring, maybe a few lines)

**Comment by bledsoef** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add docstrings and comments if necessary to files in the events logic file](https://trello.com/c/Wi87RLkZ/718-add-docstrings-and-comments-if-necessary-to-files-in-the-events-logic-file)

**Comment by thealphagurlux** [comment]
Me and John re-analyzed the comments and function descriptions, getting rid of redundant descriptions (Like delete event pretty much describes itself) and double checked to make sure that parameter types are the same as their descriptions.
