### ISSUE TITLE
Manage volunteers page breaks when inviting a cohort to a Bonner event

### ISSUE THREAD

**Issue by bledsoef** [BCStudentSoftwareDevTeam/celts#1135]
@BrianRamsay 
Just hit this error when trying to create a bonner event, adding a cohort, and trying to view the manage volunteers page.

I think error is in `rsvpForBonnerCohort`.

![Screenshot_20240219_142112](https://github.com/BCStudentSoftwareDevTeam/celts/assets/89262886/55cba91a-f49e-4e23-bb9b-e68f8655629d)

**Comment by BrianRamsay** [comment]
Resolved straight on prod!
