### ISSUE TITLE
Multiple event times of a training display as separate events

### ISSUE THREAD

**Issue by bledsoef** [BCStudentSoftwareDevTeam/celts#1156]
For events like All Volunteer Training, they will be offered multiple times, but if you attend only one it will say there are multiple programs you have not completed. We need to find a way to still have the ability for multiple offerings of the same program but make it so that multiple instances of the same training only appear as one for training eligibility. Here is an example of the problem.

![programissue](https://github.com/BCStudentSoftwareDevTeam/celts/assets/89262886/11b3da34-630a-4d5b-b758-b7d1a6a3f07c)

**Comment by bledsoef** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Multiple event times of a training display as separate events](https://trello.com/c/rL0abkHg/743-multiple-event-times-of-a-training-display-as-separate-events)

**Comment by vungc** [comment]
We came up with a solution from fixing the database and would add a new column "customEventId" which will be very similar to the recurringId and will act the same in cases like deleting multiple events. The two will differ in situations the frequency and naming. We will have to edit models, and logic, views.
