### ISSUE TITLE
Add RSVP status column to upcoming events table

### ISSUE THREAD

**Issue by Ebenezer997** [BCStudentSoftwareDevTeam/celts#116]
We need to add RSVP status to show if a user has rsvp for events or not in the upcoming events table. We try to query the RSVP status for each event in the getupcomingevents function in events.py but we were unable to get it to work.
This is what we initially tried 
```
events = (Event.select(Event, EventParticipant)
                            .join(ProgramEvent)
                            .join(Interest, on=(ProgramEvent.program == Interest.program))
                            .where(Interest.user == user)
                            .where(Event.startDate >= asOf)
                            .where(Event.timeStart > asOf.time())
                            .switch(Event)
                            .join(EventParticipant, join_type=JOIN.LEFT_OUTER)
                            .where((EventParticipant.user == user) | (EventParticipant == None))
                            .distinct()
                            .order_by(Event.eventName)
                            )
```

![image](https://user-images.githubusercontent.com/58599920/133099914-1ce6dae5-25d1-4b90-9009-7649b837ca98.png)

Neccessary files:
- _app/logic/event.py_
- _app/templates/showUpcomingEvents.html_ (if volunteer profile combined branch is merged in, then _app/templates/volunteer/volunteerProfile.html_)
- _app/controllers/events/routes.py_ (if volunteer profile combined branch is merged in, then _app/controllers/main/routes.py_)

**Comment by Ebenezer997** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #116:Add RSVP status column to upcoming events table](https://trello.com/c/ZzoUCj6J/312-celts-116add-rsvp-status-column-to-upcoming-events-table)

**Comment by mupotsal** [comment]
@hmanalai  and @Karina-Agliullova are you guys working on this. It is still under the priority queue on Trello.
