### ISSUE TITLE
The Submit and Approve button for SLC proposals is broken

### ISSUE THREAD

**Issue by andersoncedu** [BCStudentSoftwareDevTeam/celts#1163]
The button just greys out and throws a JavaScript error when trying to submit:
![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/97543993/2d2f700f-cab7-4f80-85b9-4442f11f4083)

![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/97543993/9de92dc3-8ec3-4050-a12b-877e660b4291)

**Comment by andersoncedu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Submit and approve for service learning course](https://trello.com/c/jTP44QEZ/749-fix-submit-and-approve-for-service-learning-course)

**Comment by bledsoef** [comment]
Closed in PR #1174
