### ISSUE TITLE
Instructors are labeled as Faculty for the main course proposals page.

### ISSUE THREAD

**Issue by andersoncedu** [BCStudentSoftwareDevTeam/celts#1164]
The wording for the table should say "Instructors" instead of "Faculty", or something to that effect since staff who aren't faculty are allowed to be added to the SLC proposals.

**Comment by andersoncedu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Instructors are labeled as Faculty for the main course proposals page](https://trello.com/c/dxOMFhy2/750-instructors-are-labeled-as-faculty-for-the-main-course-proposals-page)

**Comment by bledsoef** [comment]
PR was merged.
