### ISSUE TITLE
Disable Delete Event Button When Creating an Event

### ISSUE THREAD

**Issue by stevensonmichel** [BCStudentSoftwareDevTeam/celts#1165]
When an event is being created, the Delete Event button is still active. Considering that an event can be deleted unless it has been created, that button should be disabled if an event is being added for the first time. 

![delete1](https://github.com/BCStudentSoftwareDevTeam/celts/assets/112141243/35a79c01-3343-4f3c-a8d0-ab0c542bbd9f)

If one clicks on the Delete button when creating an event, it sends to this 404 page, given that the event was not created so there is no view. 

![delete2](https://github.com/BCStudentSoftwareDevTeam/celts/assets/112141243/4f4e355a-94cf-40ea-b801-6a6a676b91c9)

**Comment by stevensonmichel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Disable Delete Button When Creating an Event](https://trello.com/c/lPvMGrs0/752-disable-delete-button-when-creating-an-event)

**Comment by Hira-Ijaz** [comment]
@stevensonmichel I would like to work on this issue, please assign it to me.

**Comment by JohnCox2211** [comment]
Added if condition so that the delete button does not appear on the create page, only on the edit page. Change pulled and merged. Code starts line 281 in createEvent.html
