### ISSUE TITLE
No upcoming events is displayed on front page cards even when there are upcoming events

### ISSUE THREAD

**Issue by andersoncedu** [BCStudentSoftwareDevTeam/celts#1167]
Card displays no upcoming events
![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/97543993/c4567be0-5750-46d9-b1c1-867400589069)

even when there are upcoming events for same program
![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/97543993/19cc364d-2a32-41e4-8a2e-f107ccc57756)

**Comment by andersoncedu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ["No upcoming events" displays when there are upcoming events](https://trello.com/c/nDJpPwfQ/755-no-upcoming-events-displays-when-there-are-upcoming-events)

**Comment by bledsoef** [comment]
Closed in #1202
