### ISSUE TITLE
CELTS Admin Manage Service Learning Courses

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#117]
SRS Item: 5.6 - The CELTS administrator must be able to manage SL Course Proposals

This will be the table where CELTS admins can view and manage all service learning course proposals for the upcoming term.
![image](https://user-images.githubusercontent.com/28715731/133150309-7879fac4-5a3d-4a05-9826-3f99deaa49bf.png)

CELTS SRS: https://docs.google.com/document/d/17URsAbRVdhJ9lBABzlM3Zk7KKbmuD2m9aYMT3tG2lkw/edit
CELTS Admin Wireframe: https://balsamiq-wireframes.appspot.com/?state=%7B%22ids%22:%5B%221etrefTLsvWQntesh5_TDdC66TRVzRpHf%22%5D,%22action%22:%22open%22,%22userId%22:%22109665407847548855125%22,%22resourceKeys%22:%7B%7D%7D

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #117: CELTS Admin Manage Service Learning Courses](https://trello.com/c/RyLfxymg/313-celts-117-celts-admin-manage-service-learning-courses)

**Comment by mupotsal** [comment]
@Sandesh-L How is this issue different from what you have been working on?

**Comment by Sandesh-L** [comment]
@mupotsal We only implemented the remove course option. None of the other ones. This looks to be the admin side of the sl courses. We only built the view for the professors. The PR was merged so you can check app/templates/admin/createSLProposalTable.html for the html that we built
