### ISSUE TITLE
Negative numbers can be added to slc as number of service hours.

### ISSUE THREAD

**Issue by andersoncedu** [BCStudentSoftwareDevTeam/celts#1170]
The SLC module will need to be changed to disallow negative numbers of service hours.

**Comment by andersoncedu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Negative numbers can be added to SLC as a number of service hours.](https://trello.com/c/akjLrRPk/757-negative-numbers-can-be-added-to-slc-as-a-number-of-service-hours)

**Comment by JohnCox2211** [comment]
Created fix for issue https://github.com/BCStudentSoftwareDevTeam/celts/pull/1227

**Comment by bledsoef** [comment]
Closed in #1227
