### ISSUE TITLE
"New Proposal For Service-Learning Course" is shown for every slc course.

### ISSUE THREAD

**Issue by andersoncedu** [BCStudentSoftwareDevTeam/celts#1171]
This should probably be changed to reflect the status of the course, i.e. imported, approved.
![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/97543993/946ff129-578e-4218-a988-9d0828b27607)

**Comment by andersoncedu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ["New Proposal For Service-Learning Course" is shown for every slc course](https://trello.com/c/HnfSP8xU/758-new-proposal-for-service-learning-course-is-shown-for-every-slc-course)

**Comment by seedyjahateh** [comment]
@Ndiayem14 and I are working on this issue.

**Comment by bledsoef** [comment]
Resolved in PR #1233
