### ISSUE TITLE
Grayout the RSVP volunteers button when event has passed 

### ISSUE THREAD

**Issue by WackyWeaver** [BCStudentSoftwareDevTeam/celts#1225]
Under the Manage Volunteers tab for an event. The button appears green even after the event has passed. 

![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/156225590/31e425e3-1e98-4524-899d-6af4e70c30f2)

![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/156225590/bcef6f7d-f995-4e2e-b51a-3ca787712c57)

**Comment by WackyWeaver** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Grayout the RSVP volunteers button when event has passed #1225](https://trello.com/c/wB3LM6Zo/766-grayout-the-rsvp-volunteers-button-when-event-has-passed-1225)

**Comment by bledsoef** [comment]
@WackyWeaver I am closing this issue. It does not seem necessary. If you disagree feel free to reopen and let me know why!
