### ISSUE TITLE
Indicate if an event is currently in progress

### ISSUE THREAD

**Issue by BrianRamsay** [BCStudentSoftwareDevTeam/celts#1228]
Since we have both `isPastStart` and `isPastEnd`, we can show more detail than if an event is in the past. We should also add a banner on all the event views that indicates if an event is in progress.

**Comment by BrianRamsay** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Indicate if an event is currently in progress](https://trello.com/c/49ucZV8o/767-indicate-if-an-event-is-currently-in-progress)

**Comment by bledsoef** [comment]
Closed by PR #1231
