### ISSUE TITLE
Firefox Event date dropdown not working

### ISSUE THREAD

**Issue by WackyWeaver** [BCStudentSoftwareDevTeam/celts#1236]
The event date dropdown menu under "Create Event" does not work on firefox, but it works perfectly fine on chrome. 

Firefox (Nothing):
![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/156225590/1d92fdb1-61c0-4fd3-b3db-ab7b71f834a8)
Chrome: 
![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/156225590/a3c6462b-c727-4090-bab0-f3d68e8e63ca)

**Comment by bledsoef** [comment]
Closed in PR #1260
