### ISSUE TITLE
Inconsistency in the number of courses in the Term dropdown in Chrome and Firefox browsers 

### ISSUE THREAD

**Issue by ali-ramazani** [BCStudentSoftwareDevTeam/celts#1238]
In the Create Event page, more terms are displayed on the Firefox browser than the Chrome browser. More specifically, when creating an event on Firefox browser, the Term dropdown displays all the terms; however, on Chrome, only 3 terms are shown. 

Below is how it looks on Firefox. 
![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/112561860/17671d46-2066-4d05-8897-7709a0165859)

Below is how it looks on Chrome.
![Screenshot (3)](https://github.com/BCStudentSoftwareDevTeam/celts/assets/112561860/b548b466-e5f2-4a52-a935-87a487ee5689)

**Comment by bledsoef** [comment]
Cannot replicate the issue you are seeing, and since you weren't able to either in Trello I will close this.
