### ISSUE TITLE
Course Withdrawal doesn't work on Chrome; only works on Firefox. 

### ISSUE THREAD

**Issue by ali-ramazani** [BCStudentSoftwareDevTeam/celts#1239]
In Course Proposals, when a user tries to withdraw a course, it works on Firefox, but it doesn't work on Chrome. More specifically, the withdraw button doesn't lead to any action when attempted on Chrome; however, it works fine on Firefox.

**Comment by bledsoef** [comment]
![Screenshot 2024-08-22 at 3 04 01 PM](https://github.com/user-attachments/assets/07429dba-a6c6-4e0d-8532-b7d96bbd1544)
This is what I get when attempting to withdraw a course, on Chrome
