### ISSUE TITLE
Course proposal page breaks after a proposal file is uploaded 

### ISSUE THREAD

**Issue by ali-ramazani** [BCStudentSoftwareDevTeam/celts#1241]
In course proposals, when a user selects the action 'edit', and upload the course syllable, the upload will be successful. However, when trying to view the proposal, the page breaks whenever the user wants to view or edit a course proposal with the 'in progress' status.

**Comment by ali-ramazani** [comment]
We fixed the issue, which was caused by an index error when trying to get the index of "/" from the string. We fixed the issue by adding an if-else statement to avoid the error. The page works without any error.

**Comment by Karina-Agliullova** [comment]
PR was merged
