### ISSUE TITLE
Unapprove button doesn't work for courses in review course proposal

### ISSUE THREAD

**Issue by ali-ramazani** [BCStudentSoftwareDevTeam/celts#1244]
When approving courses in course review proposals, it works. However, when trying to unapprove  a course from Approved courses list, the button doesn't work and the course is not removed/unapproved. 

![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/112561860/0658b872-4ba5-4592-b902-3d72f8157529)

**Comment by bledsoef** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unapprove button doesn't work for courses in review course proposal](https://trello.com/c/f6VpSKXH/773-unapprove-button-doesnt-work-for-courses-in-review-course-proposal)
