### ISSUE TITLE
Creating an undo button for event deletion 

### ISSUE THREAD

**Issue by WackyWeaver** [BCStudentSoftwareDevTeam/celts#1261]
Whenever an event is deleted, even within the same session, the change is permanent. Make the ability for the user in the same session to undo the deletion of an event. Preferable add a pendingDeletion field to remove the instances after a given time or session.

**Comment by bledsoef** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Creating an undo button for event deletion #1261](https://trello.com/c/jqfFzMYb/774-creating-an-undo-button-for-event-deletion-1261)

**Comment by bledsoef** [comment]
Closed in #1286
