### ISSUE TITLE
'timeStr is not defined' issue in createEvent.html

### ISSUE THREAD

**Issue by ali-ramazani** [BCStudentSoftwareDevTeam/celts#1262]
When you inspect createEvent.html in the browser development console, there's an issue with the format24to12HourTime function with the timeStr parameter. The problem is specifically due to the function performing operations such as slicing on the timeStr; however, the string doesn't exist or is not passed (correctly) into the function. 

![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/112561860/1c42ecc7-4baa-4eaf-a1f3-e4db05e28927)

**Comment by bledsoef** [comment]
Resolved in issue #1278
