### ISSUE TITLE
Grammatical error under CELTS-sponsored event

### ISSUE THREAD

**Issue by vungc** [BCStudentSoftwareDevTeam/celts#1263]
Change “A CELTS-event” to “a CELTS-event” in event creation under CELTS-sponsored event

**Comment by vungc** [comment]
![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/112138502/1eaaba37-f07b-4c97-aa00-b9e986dcf0ff)

**Comment by Mbeweg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Grammatical error under CELTS-sponsored event](https://trello.com/c/KqQRg69w/777-grammatical-error-under-celts-sponsored-event)

**Comment by bledsoef** [comment]
Closed in PR #1264
