### ISSUE TITLE
Add Icons to the Courses status in Course Managment

### ISSUE THREAD

**Issue by Ndiayem14** [BCStudentSoftwareDevTeam/celts#1273]
In our course management system, we've integrated various user status icons using FontAwesome. These icons include statuses such as Submitted, Approved, and In Progress, among others.

**Comment by eunsungw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Added Icons to the Course Status in Course Management](https://trello.com/c/ZJaOlc8s/782-added-icons-to-the-course-status-in-course-management)

**Comment by bledsoef** [comment]
Resolved in issue #1272
