### ISSUE TITLE
Removing gap and creating two separate lists on Create an Event Page

### ISSUE THREAD

**Issue by vungc** [BCStudentSoftwareDevTeam/celts#1274]
Weird spacing was caused by a class added on the "All Volunteer Training" that purposely added a gap. We talked to Dr. Heggen and he said the bigger issue is on why that gap was created and it was because All Volunteer Training is not a program and that solving the real issue would mean we would have to find a new way to separate it from programs. We are combing this small issue with another issue on teh google doc to create two separate lists. We got rid of the div with the class and we are now going to create two lists with headers "Program Events" on the left side and "Templates" on the right side.

**Comment by Mbeweg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Removing the gap in the Create Event page](https://trello.com/c/G8j1gCaM/783-removing-the-gap-in-the-create-event-page)

**Comment by bledsoef** [comment]
Closed in #1275
