### ISSUE TITLE
Add instructions on how to enter B# on Kiosk Entry & Adding an Enter Button 

### ISSUE THREAD

**Issue by eunsungw** [BCStudentSoftwareDevTeam/celts#1276]
There are no specific instructions on how the user can enter the B# on the Kiosk Entry such as if they need to enter the B# with no letter or just the numbers or with the "B" included with the numbers. There is no button for the user to click to enter the B#, the user has to press "Enter" to submit the B# but there is no instruction for it, so adding an Enter Button would be good for the Web Application.

**Comment by eunsungw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add instructions on how to enter B# on Kiosk Entry & Adding an Enter Button](https://trello.com/c/GM7x3u6H/784-add-instructions-on-how-to-enter-b-on-kiosk-entry-adding-an-enter-button)

**Comment by bledsoef** [comment]
Merged in PR #1277
