### ISSUE TITLE
All Volunteer Training Template Title

### ISSUE THREAD

**Issue by vungc** [BCStudentSoftwareDevTeam/celts#1279]
When the All Volunteer Training template is clicked, the title says "Create a CELTS-Sponsored Event" but it should say "Create All Volunteer Training"

![image](https://github.com/user-attachments/assets/ffbd1d92-d45b-496b-9787-6da62d049302)

**Comment by Mbeweg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [All Volunteer Training title](https://trello.com/c/131o6vEN/785-all-volunteer-training-title)

**Comment by bledsoef** [comment]
Closed in #1280
