### ISSUE TITLE
Program Completion in CCE Minor Management

### ISSUE THREAD

**Issue by vungc** [BCStudentSoftwareDevTeam/celts#1283]
When the sustained engagement is 4/4 and the summer experience is complete, then the program can be marked complete. We will need to create a new column with icons for complete and incomplete and we will be implementing the same icons that were used in another area, the course management.
This is the area where the issue is:
![image](https://github.com/user-attachments/assets/bdbcf5a1-2cd5-4f59-b48a-0337ba3bc9cf)

These are the same icon styles that we will be using:
![image](https://github.com/user-attachments/assets/76f07ada-a3a9-4783-97ca-16f693de1b79)

**Comment by Mbeweg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Program Completion of the CCE Minor Management System](https://trello.com/c/S7iJjjBp/786-program-completion-of-the-cce-minor-management-system)

**Comment by bledsoef** [comment]
@vungc, to clarify, is there a difference between this issue and issue #1149?

**Comment by bledsoef** [comment]
@vungc if there is, feel free to reopen, but for now am closing this as it was resolved in #1284
