### ISSUE TITLE
Whenever toggling the Event requires RSVP, the food is provided button toggles too

### ISSUE THREAD

**Issue by WackyWeaver** [BCStudentSoftwareDevTeam/celts#1287]
In Create Events page

There is some sort of expectation of food whenever an event requires an RSVP. Both of the toggles go on when the RSVP toggle is clicked.

**Comment by WackyWeaver** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Whenever toggling the Event requires RSVP, the food is provided button toggles too #1287](https://trello.com/c/Uowk2ivE/787-whenever-toggling-the-event-requires-rsvp-the-food-is-provided-button-toggles-too-1287)

**Comment by WackyWeaver** [comment]
Contact Sarah or Ashley to ask whether that was a feature that they wanted.

**Comment by bledsoef** [comment]
Closed in #1292
