### ISSUE TITLE
Create Events Page: Split the toggle buttons into 2 sections, and make one of 3 required to create Event

### ISSUE THREAD

**Issue by thealphagurlux** [BCStudentSoftwareDevTeam/celts#1294]
Spilt the toggle section under description in the create events page into 2 groups: 

Section 1: Is the event going to have food || Is RSVP required?

Section 2: make one of these three required: 
Training || Service hours || Bonner event -

The Bonner event toggle button will need to be added as well.

<img width="952" alt="image" src="https://github.com/user-attachments/assets/dc05e87b-ff16-443b-aa86-c6de8a403d5c">

**Comment by bledsoef** [comment]
PR #1296 was merged
