### ISSUE TITLE
LSF Pending form errors

### ISSUE THREAD

**Issue by Karina-Agliullova** [BCStudentSoftwareDevTeam/celts#1322]
Labor Dept. student workers get the pending forms error

**Comment by Karina-Agliullova** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [LSF Pending form errors](https://trello.com/c/7KAEDHht/809-lsf-pending-form-errors)

**Comment by bledsoef** [comment]
@Karina-Agliullova could I get anymore background on this issue?
