### ISSUE TITLE
LSF email notifications not working

### ISSUE THREAD

**Issue by Karina-Agliullova** [BCStudentSoftwareDevTeam/celts#1325]
Email notifications for adjustments in LSF aren't being sent

**Comment by Karina-Agliullova** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [LSF email notifications not working](https://trello.com/c/t7F2jJdD/812-lsf-email-notifications-not-working)

**Comment by ojmakinde** [comment]
Emails work now. Reached out to LSF users and they confirmed functionality.
