### ISSUE TITLE
Date Field Editing in Event with Multiple Offering modal

### ISSUE THREAD

**Issue by stevensonmichel** [BCStudentSoftwareDevTeam/celts#1330]
Inside the modal for Event with Multiple Time Offering, the Date field is not editable. The only way to have a date is to select it from the Date Picker.

**Comment by stevensonmichel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Date Field Editing in Event with Multiple Offering modal](https://trello.com/c/gVojORXr/814-date-field-editing-in-event-with-multiple-offering-modal)

**Comment by ojmakinde** [comment]
Closing this issue because it is part of the larger datepicker fix issue mentioned in #1333
