### ISSUE TITLE
Refactor Multiple Event Offering and Recurring Event logic

### ISSUE THREAD

**Issue by vungc** [BCStudentSoftwareDevTeam/celts#1335]
TBD

**Comment by vungc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor Multiple Event Offering and Recurring Event logic](https://trello.com/c/APWJg4wJ/817-refactor-multiple-event-offering-and-recurring-event-logic)

**Comment by ojmakinde** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor UI for Multiple Offerings and Recurring Events](https://trello.com/c/Myb8l74Y/824-refactor-ui-for-multiple-offerings-and-recurring-events)
