### ISSUE TITLE
Error saving single events when start date is not specified

### ISSUE THREAD

**Issue by ojmakinde** [BCStudentSoftwareDevTeam/celts#1336]
When creating an event, if the start date is not specified and the 'Save' button is clicked, the browser attempts to save the event and raises an error. Ideally, a validation checker should catch that error and prevent a save.

This behavior was likely introduced with the development of Multiple Events.

Images below:
_Before saving:_
<img src="https://github.com/user-attachments/assets/82d7b4bb-d5dd-44ce-9885-236112a7b2b7" width=300 />

_After saving:_
<img src="https://github.com/user-attachments/assets/4a018203-75c8-4537-9579-db6276d3ffc1" width=300 />

**Comment by ojmakinde** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Error saving single events when start date is not specified](https://trello.com/c/FMwDUShm/819-error-saving-single-events-when-start-date-is-not-specified)

**Comment by hoerstl** [comment]
Issue fixed in branch `1306-Multiple-Offering-Duplicate-Entries`
