### ISSUE TITLE
Bonner Cohort Selection

### ISSUE THREAD

**Issue by Karina-Agliullova** [BCStudentSoftwareDevTeam/celts#1344]
When we create a Bonner Scholars Event, we can invite Bonner cohort or cohorts, using the checkbox. Once the cohort is selected, it creates a Bonner Scholars Event with volunteers that were in the Bonner cohort selected. However, if we start editing that event, the checkbox is unchecked, which allows us to select the exact same cohort, even though the volunteers would still be the same. The checkbox doesn't keep consistency when we check it, which makes it confusing. The checkbox should keep being checked when we check it, even after we go into editing the event.
![Screenshot (13)](https://github.com/user-attachments/assets/b55e0e07-b5ac-495a-9986-c58c6acdddc2)
![Screenshot (14)](https://github.com/user-attachments/assets/e7053cb0-0f92-47a8-90d4-1cf422bc4e06)

**Comment by hoerstl** [comment]
Excellent issue creation but this is a duplicate issue of issue #1295. This is being worked on in PR [https://github.com/BCStudentSoftwareDevTeam/celts/pull/1297](url). Therefore, I shall close this issue and delete the trello card.
