### ISSUE TITLE
Events With No Program in Event List

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#138]
Right now, events with no program do not show up in any part of the event list interface.  We would like them to show up on the tab for "One-time Events."

![image](https://user-images.githubusercontent.com/28715731/135513664-06d6ebd1-f64b-42e9-932b-30bfdc814e86.png)

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #136: Events With No Program in Event List](https://trello.com/c/7UperOxm/321-celts-136-events-with-no-program-in-event-list)

**Comment by Boorclark** [comment]
Note to self --> Rename "One-time Events" to "Other Events" due to them having the ability to be recurring. Also address "One-off Event" on creation page.

**Comment by Boorclark** [comment]
This issue was fixed with PR 330 and it has been merged. Closing issue.
