### ISSUE TITLE
Change to Track Volunteers Add Volunteers Button

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#139]
The button for admins to add volunteers to an event is confusing.  The search bar makes it seem like you look them up there and then use the add button to add them in which is not the case.  We should remove the search bar on the table unless the table is paginated, and then just make the add volunteer button a standard button with clear naming as to what it does.

![image](https://user-images.githubusercontent.com/28715731/135640549-9eb21665-ebc3-4fea-8458-be742d33821f.png)

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #139: Change to Track Volunteers Add Volunteers Button](https://trello.com/c/GFJJmaE9/322-celts-139-change-to-track-volunteers-add-volunteers-button)

**Comment by bledsoef** [comment]
No longer an issue.
