### ISSUE TITLE
Track Volunteers Table Must Support EventRsvp

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#142]
With the new changes to the database and the addition of the RSVP table, we need to update which volunteers show up in the table (both when added and when the volunteer RSVPs.)  It will either be those who are in the EventParticipant table or the RSVP table, leaning more towards the those in the RSVP table.  If the volunteers that are added to the table are pulled from the RSVP table, then when volunteers RSVP for events, they need to be added to the RSVP table instead of the EventParticipant table.

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #142: Change to Track Volunteers Table](https://trello.com/c/WNsJ62LJ/324-celts-142-change-to-track-volunteers-table)

**Comment by hmanalai** [comment]
PR #147 fixes this issue as well.
