### ISSUE TITLE
Remove RSVP Button from Create Event Template

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#151]
When creating an event, the RSVP button should not be there.  We'll need to remove it since it causes errors when clicked.

![image](https://user-images.githubusercontent.com/28715731/138475250-1261724d-5f81-491e-8db0-e466a5c2d5bb.png)

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #151: Remove RSVP Button from Create Event Template](https://trello.com/c/XJCD7ORX/327-celts-151-remove-rsvp-button-from-create-event-template)

**Comment by Boorclark** [comment]
@BrianRamsay I believe this issue can be resolved. The issue has already been fixed.
