### ISSUE TITLE
Reorganize Files

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#154]
Our file structure could use a rework.  Some things to do include:
- In templates, the main directory only holds a file called home.html which is not needed anymore and can be deleted.
- searchStudentPage.html should be added to the admin directory.
- The main directory in the controllers should probably be changed to volunteer since it is mostly volunteer functionality

There is more, but this is is a start.

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #154: Reorganize Files](https://trello.com/c/xAVxG8qY/330-celts-154-reorganize-files)

**Comment by bledsoef** [comment]
PR merged closing issue.
