### ISSUE TITLE
Adding Users to CELTS

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#157]
We'll need a way to get users in our CELTS database.  Brian suggested implementing like CAS does it from Active Directory.  Whoever takes this issue should investigate how CAS is implementing this and translate that over to CELTS.  The CAS file it is implemented in is _sync_faculty.py_

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #157: Adding Users to CELTS](https://trello.com/c/PICjfh4D/332-celts-157-adding-users-to-celts)

**Comment by Boorclark** [comment]
This issue is being addressed in Issue #257 and PR #319. We are using Tracy currently but once we get approval we will switch to AD. Closing issue.
