### ISSUE TITLE
Sidebar Doesn't Extend to the Length of the Page

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#171]
Our sidebar isn't extending the whole length of the page.  I'm pretty sure this affects all pages.

![image](https://user-images.githubusercontent.com/28715731/139723119-ca0612be-3731-4b74-b4b8-7700fe6a677c.png)

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #171: Sidebar Doesn't Extend to the Length of the Page](https://trello.com/c/6Me82YLs/338-celts-171-sidebar-doesnt-extend-to-the-length-of-the-page)

**Comment by sreynit02** [comment]
We were not able to get the sidebar to extend. But we removed the dark "space" to the right of the sidebar. This change is committed to branch 'fix-sidebar' .
