### ISSUE TITLE
Admin Management Search Bars Not Updating Correctly

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#175]
On the admin management page, when an admin is adding CELTS admins and CELTS student staff, the search bar doesn't work as expected.  The user is able to make a user a CELTS admin when they already are one, and they are able to remove someone from being a CELTS admin when they aren't one.  We need to handle these cases and give appropriate flash messages for them to make it clear to the user what happened.

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #175: Admin Management Search Bars Not Updating Correctly](https://trello.com/c/f32k9dsV/339-celts-175-admin-management-search-bars-not-updating-correctly)

**Comment by mupotsal** [comment]
This is on PR 181: https://github.com/BCStudentSoftwareDevTeam/celts/pull/181
