### ISSUE TITLE
Time Selectpickers do not Work on Firefox Browser

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#176]
When creating and editing an event, the time selectpickers are not supported on Firefox browsers.  We'll need to replace them with a time selectpicker that will work on Firefox.

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #176: Time Selectpickers do not Work on Firefox Browser](https://trello.com/c/rP3JyTOd/340-celts-176-time-selectpickers-do-not-work-on-firefox-browser)

**Comment by mupotsal** [comment]
This is also an issue for Safari.

**Comment by sreynit02** [comment]
Liberty and I worked on it but there needs to be some more exploration with the time picker. We left off with this PR#191: https://github.com/BCStudentSoftwareDevTeam/celts/pull/191

**Comment by hmanalai** [comment]
The same issue is happening with the flash messages. The screen reader reads them correctly on Chrome and Edge, but not on firefox.

**Comment by hmanalai** [comment]
Fixed in PR #191
