### ISSUE TITLE
Add functionality to "last email sent to" in the email modal

### ISSUE THREAD

**Issue by Sandesh-L** [BCStudentSoftwareDevTeam/celts#187]
![image](https://user-images.githubusercontent.com/46611742/140556991-e9e71293-423f-48f7-bedf-5906ad4df5f4.png)
It should show the last email sent for that event. And the date. clicking on the email button on the event_list page will always show the same modal. That means that there needs to be an ajax request sent after the email button has been clicked.

**Comment by bledsoef** [comment]
Missing log for sender of email in emailLog.py. Need to insert the sender whenever a new email is sent by checking who the user was who was logged in. Insert new spot in email template front end for information to go.

**Comment by bledsoef** [comment]
We have updated emailLog and emailHandler to include a sender field. Now we need to test that the emails are being stored properly, and then write a function that has a sort query to get the last sent email for a particular event_id.

**Comment by Boorclark** [comment]
This issue was merged into development in #305. Closing issue.
