### ISSUE TITLE
Matching Volunteers to Outside Participants

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#192]
One missing feature needed on some program's events (Berea Buddies, Tutoring, etc.) is the ability to match volunteers with outside participants.

![image](https://user-images.githubusercontent.com/28715731/140958072-cafb8ce9-1847-4937-b4a2-c713fe5e59dc.png)

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS administrator must be able to match volunteers to outside participants](https://trello.com/c/pf9iSaer/286-celts-administrator-must-be-able-to-match-volunteers-to-outside-participants)

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #192: Matching Volunteers to Outside Participants](https://trello.com/c/ljnvyNzx/343-celts-192-matching-volunteers-to-outside-participants)

**Comment by Boorclark** [comment]
This feature is not going to be developed right now. Closing issue.
