### ISSUE TITLE
Fix Search User Logic

### ISSUE THREAD

**Issue by hmanalai** [BCStudentSoftwareDevTeam/celts#199]
**Issue**: Currently the search user logic only searches by the first name if the user is a student. This needs to be fixed to include all users. 

**New Feature**: We also need to add new code so that we can filter the search result by faculty, student, celts admin, and celts student admins.

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #199: Fix Search User Logic](https://trello.com/c/db2n9bfe/366-celts-199-fix-search-user-logic)

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #40: Add File Upload To Event Creation](https://trello.com/c/EzKDiapl/349-celts-40-add-file-upload-to-event-creation)
