### ISSUE TITLE
Add "Eligible Students" category to "to" when Emailing

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#201]
We would like another option to be able to send to eligible students when emailing for an event.

![image](https://user-images.githubusercontent.com/28715731/142919976-8182e250-fdd2-4999-8dcf-4fa1a17552fa.png)

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #201: Add "Eligible Students" category to "to" when Emailing](https://trello.com/c/V68ljjb2/368-celts-201-add-eligible-students-category-to-to-when-emailing)

**Comment by Ebenezer997** [comment]
Does this issue build up from another issue of sending emails to students or this issue is independent and should be done from scratch

**Comment by hmanalai** [comment]
> Does this issue build up from another issue of sending emails to students or this issue is independent and should be done from scratch

There is PR #210 in for email handler functionality that will make implementing this feature quite easy. So I would wait until that PR is in and then implement.
