### ISSUE TITLE
Send Reminder Emails for Recurring Events

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#202]
We want the emailer to be able to automatically send reminder emails for events that are recurring once the date happens each week.  We would want this to possibly send to outside participants, too.

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #202: Send Reminder Emails for Recurring Events](https://trello.com/c/LRZkQJd0/369-celts-202-send-reminder-emails-for-recurring-events)

**Comment by Boorclark** [comment]
Notes:
- After talking with Anderson we most likely will not be using an API like Twilio and instead be searching the DB (event participant I am assuming) for emails that have already been sent to the participants of events. I think this may be helpful in the future: https://stackoverflow.com/questions/4455282/call-a-javascript-function-at-a-specific-time-of-day
https://stackoverflow.com/questions/52022134/how-do-i-schedule-an-email-to-send-at-a-certain-time-using-cron-and-smtp-in-pyt

**Comment by Boorclark** [comment]
Notes:
 - As far as actual code goes, I believe an emailer should be able to search the event_id in the event participant DB. From here, they can get all participants with that event_id and send them an automated email. I think the best way for outside participants is to allow the emailer to choose events that may relate to the one for which they are sending the email. Also just a note for the future, I believe the only person who would have access to this page would be the accounts that manage certain events and admins. 

- Adding a section for reoccurring into the following picture may be the best way to go about this. We may add a section in "To" to something along the lines of "All previous Participants"
![image](https://user-images.githubusercontent.com/97637517/173676225-7d67bd0f-6bff-473c-b727-8be4feb39ceb.png)

**Comment by Boorclark** [comment]
Notes: 
 - Once Issue #187 has been resolved we may be able to look into how they stored the "latest" email and apply that to saving a recurring email. 
 -  Function to view event participants for reminder emails
 -  Potentially use smtplib module for automation with a date module
