### ISSUE TITLE
Datepicker Start/End Date Logic Breaks in Firefox and Safari

### ISSUE THREAD

**Issue by hmanalai** [BCStudentSoftwareDevTeam/celts#219]
If the start date is selected then the dates before the start date should not be selectable as an end date, and vice versa. However, this functionality breaks in Firefox and Safari. Works in Chrome, and Edge. 

files:
`createSingleEvent.html`
`createEvents.js`

Note: The javascript datepicker seems to have accessibility issues. The dates inside the datepicker are read as `blank` by the screen reader. See if this is an issue we can fix.

**Comment by Boorclark** [comment]
Fixed by hmanalai https://github.com/BCStudentSoftwareDevTeam/celts/pull/191#issuecomment-1069459724.
Closing Issue.
