### ISSUE TITLE
Service Learning Courses Admin Review Interface

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#232]
Admins should be able to go into a separate interface for reviewing course proposals that are in the pending table in the SL course management interface.  They'll go to this interface through the Service Learning Course Proposal Management interface.  (There currently isn't a link to this page in the sidebar so the route is: <ipAddress>:8080/courseManagement/<term>)

![image](https://user-images.githubusercontent.com/28715731/158688950-9ce9be6a-475b-4585-b523-f77abdb7bcac.png)

Here is the wireframe for this interface (the slides titled 4. Admin Review): https://balsamiq-wireframes.appspot.com/?state=%7B%22ids%22:%5B%221etrefTLsvWQntesh5_TDdC66TRVzRpHf%22%5D,%22action%22:%22open%22,%22userId%22:%22109665407847548855125%22,%22resourceKeys%22:%7B%7D%7D

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #232: Service Learning Courses Admin Review Interface](https://trello.com/c/M9u2Wtp8/382-celts-232-service-learning-courses-admin-review-interface)

**Comment by Boorclark** [comment]
Issue Merged. Closing
