### ISSUE TITLE
Link Admin Service Learning Course Proposal Management in Sidebar

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#233]
Currently there is no link to the below page, the SL course proposal management page for admins

![image](https://user-images.githubusercontent.com/28715731/158689632-7a87febb-3491-4b9e-845a-35a04b9360e1.png)

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #233: Link Admin Service Learning Course Proposal Management in Sidebar](https://trello.com/c/pxpcuXoT/383-celts-233-link-admin-service-learning-course-proposal-management-in-sidebar)

**Comment by tylerpar99** [comment]
@bryantal I believe this might be an outdated issue. I think if you check development there is already a course management page for admins.
