### ISSUE TITLE
Celts Frontend Style Guide

### ISSUE THREAD

**Issue by romano-w** [BCStudentSoftwareDevTeam/celts#24]
A simple style guide including color palettes, font sizing and families, and other layout practices should be implemented for usability, consistency, and visual appeal. Many if not most of these can follow what Bootstrap provides, but a single-page document that lays out our decisions would be useful for reference.

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #24: Celts Frontend Style Guide](https://trello.com/c/uuaGoUcz/350-celts-24-celts-frontend-style-guide)

**Comment by bledsoef** [comment]
Issue is likely no longer relevant, closing for now.
