### ISSUE TITLE
Event Time Selector Throws and Error When Selecting Minutes

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#242]
When creating a new event, if you select the time to have minutes (such as 10:30 instead of 10:00), there will be an error and the event will not be created.  If you mark the event as requiring RSVP, then the event will get created.  This will need more investigation.
Here is the console error it gives:
![image](https://user-images.githubusercontent.com/28715731/164533460-bb4a4a75-b0c2-4334-a4b2-3a28d3f463f1.png)

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #242: Event Time Selector Throws and Error When Selecting Minutes](https://trello.com/c/B9jZQtAn/387-celts-242-event-time-selector-throws-and-error-when-selecting-minutes)

**Comment by Boorclark** [comment]
Note:
- We came to the conclusion that the root of this issue is storing the am vs pm on the time slots. If you select two times in the am or pm it's fine but when you do am and pm an error is thrown.

**Comment by Boorclark** [comment]
Note:
 - New update is that some of the PMs in the DB are converting to AMs and being stored not in 24hr time. We have to look into what is causing this error.

**Comment by mohamudm1** [comment]
Note: 

On the createSingleEvents.html file, there might be an issue with the time formatting. Eg. Instead of using %I on the ("%I: %m %p") it might be a good idea to use %H which represents a 24-hour format!

**Comment by Boorclark** [comment]
This issue was fixed with PR 301 and it has been merged. Closing issue.
