### ISSUE TITLE
Too Many Database Queries on Volunteer Profile View

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#245]
When going to a volunteers profile, the database is queried around 80 times.  Let's investigate how we can reduce the amount of queries since we are only viewing the page.

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #245: Too Many Database Queries on Volunteer Profile View](https://trello.com/c/Akc2lOy9/390-celts-245-too-many-database-queries-on-volunteer-profile-view)

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #246: Background Check Table Below Footer #246](https://trello.com/c/H06Ung5P/391-celts-246-background-check-table-below-footer-246)

**Comment by Lyisus** [comment]
Made pull request #314 in order to address this issue but could still be worked on further in the future.

**Comment by Boorclark** [comment]
Issue Merged. Closing
