### ISSUE TITLE
Proposal Management under the admin view should be merged with the Service learning page.

### ISSUE THREAD

**Issue by tylerpar99** [BCStudentSoftwareDevTeam/celts#251]
Currently, there is a Service learning page and a separate Proposal Management page under the Admin dropdown. Brian has proposed that these two pages are similar enough to warrant merging them into one. This would also avoid the confusing naming between Course Proposal and Proposal Management.

![image](https://user-images.githubusercontent.com/67805799/165375911-c1ba4b2c-2132-4733-8b5a-e08eb0fbba17.png)

**Comment by tylerpar99** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #251: Proposal Management under the admin view should be merged with the Service learning page.](https://trello.com/c/btFrXUnn/399-celts-251-proposal-management-under-the-admin-view-should-be-merged-with-the-service-learning-page)

**Comment by tylerpar99** [comment]
https://trello.com/c/btFrXUnn/399-celts-251-proposal-management-under-the-admin-view-should-be-merged-with-the-service-learning-page

**Comment by bledsoef** [comment]
Pull request merged.
