### ISSUE TITLE
allTrainingsEvent query is not handling when no events exist which causes an error if a term has no events.

### ISSUE THREAD

**Issue by tylerpar99** [BCStudentSoftwareDevTeam/celts#252]
The query titled `allTrainingsEvent` is not handling a situation in which no events exist for the current term. This causes an error when this term is active.

**Comment by tylerpar99** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #252 allTrainingsEvent query is not handling when no events exist which causes an error if a term has no events.](https://trello.com/c/sJPqJdrX/400-celts-252-alltrainingsevent-query-is-not-handling-when-no-events-exist-which-causes-an-error-if-a-term-has-no-events)

**Comment by bledsoef** [comment]
Pull request merged.
