### ISSUE TITLE
Add Continuity Between Recurring Events

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#255]
There should be an option to import volunteers from the last time the event was created when they go into add volunteers to the track volunteers table.  This will mainly be for when the admins create recurring events, and then have to go into the events to add the volunteers.

**Comment by bledsoef** [comment]
Create an ajax request in JavaScript using the volunteers.py addPastVolunteers controller method. Call the JavaScript function onclick in our button in HTML to get the data from the controller onto the webpage.

**Comment by Boorclark** [comment]
Issue Merged. Closing
