### ISSUE TITLE
Give Admins Ability to Add Staff as Potential Course Instructors

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#256]
Admins need to have the ability to add staff who can be instructors of Service Learning Courses on the Manage Service Learning Faculty Page (we may have to change the title to be less confusing, too).  There should be a button that lets them create a user, and then they are added to the course instructor's table.  These created users should show up in the table on the Manage Service Learning Faculty Page, and they should show up on the search bar for adding instructors when creating a new course proposal.

http://<YOUR-IP>:8080/manageServiceLearning

![image](https://user-images.githubusercontent.com/28715731/165981027-d1423fcd-90fa-43ce-a0e0-9cf60f69e72a.png)

**Comment by Boorclark** [comment]
This is no longer an issue as now you are able to add Student Staff, Admin, and Faculty (Staff).

![image](https://user-images.githubusercontent.com/97637517/179570069-c4b0bb14-2c93-4028-8d72-d4cb114907b2.png)
