### ISSUE TITLE
Add "All Eligible" Option to Email Modal

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#258]
When admins are setting who the email for an event is sent to, there should be option to choose eligible volunteers to email in the dropdown. (This is everyone who has completed the All-Volunteer Training, completed and passed all background checks, and are not banned)

![image](https://user-images.githubusercontent.com/28715731/165982287-36ae023a-3c9d-415f-acc7-8e84b4fdaa5d.png)

**Comment by Boorclark** [comment]
Notes:
  - Look through all users in event participant DB and in the background check DB
  - Look at event Ids and look for 14 (AVT)
  - If users passed FBI, CAN, and SHS then they can be displayed to admin

**Comment by Boorclark** [comment]
Never mind we goofed. This is the same as Issue #201 and Anderson is working on this same issue. This issue can be deleted.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #258: Add "All Eligible" Option to Email Modal.](https://trello.com/c/FoH17sME/401-celts-258-add-all-eligible-option-to-email-modal)
