### ISSUE TITLE
Admin Logging Needs to be Added to Each Significant Action

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#266]
We need to add functionality to record admin logs for more of the actions that admins and student staff in the application.  For example, logs do not get recorded when an admin bans/unbans a volunteer.

routes: http://[YOUR-IP]:8080/adminLogs

**Comment by Boorclark** [comment]
This issue was fixed with PR 290 and it has been merged. Closing issue.

**Comment by Boorclark** [comment]
I was a bit wrong. This issue is still up in the air kind of. Reopening
