### ISSUE TITLE
Ensure Admin Pages Check Permissions Properly

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#268]
Some admin pages in CELTS also restrict access if the user is a student staff when they shouldn't.  We need to make sure CELTS student staff can access the event pages they are program managers for.  Right now, program managers can edit the event they are program managers for, but they cannot view the track volunteers page.  Check the database and make your user is a program manager for certain program, so you can test if they can view the corresponding event pages.

files: /app/controllers/admin/volunteers.py

It would also be a good idea to check all of the controller files in /app/controllers/admin to see if they are checking permissions correctly.

**Comment by Boorclark** [comment]
This issue was fixed with PR 299 and it has been merged. Closing issue.
