### ISSUE TITLE
Admin Create SLC Doesn't Take User Back to Admin SLC Interface

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#271]
When an admin goes to create a service learning course proposal, if they submit the proposal or hit cancel, it will take them to the faculty course proposal interface.  It redirect them back to the admin course proposal interface instead.

routes: <YOUR-IP>:8080/manageServiceLearning

![image](https://user-images.githubusercontent.com/28715731/169843773-7d60d043-993d-4022-a3ea-4ba8810142ba.png)

**Comment by Boorclark** [comment]
The PR for this issue has been merged, closing Issue.
