### ISSUE TITLE
Faculty View in CELTS

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#272]
If the user is a faculty, the landing page they get is the event list, and they do not have access to their course proposal management page in the sidebar.  We should change this to make the course proposal management page the page they see when they log in, and that is the only page they should have access to in the sidebar.

![image](https://user-images.githubusercontent.com/28715731/169845207-70d68988-a0e9-4bdd-895e-2040eb894cb3.png)

**Comment by Boorclark** [comment]
PR 272 solved this issue and this has been merged. Closing issue.
