### ISSUE TITLE
Change studentmanager Table

### ISSUE THREAD

**Issue by Lyisus** [BCStudentSoftwareDevTeam/celts#298]
Extends from issue #268 

The studentmanager table has a name that can lead to confusion as it is used to connect users to the programs they are managers of. A more appropriate name would be programmanager. This requires a refactor of the appropriate models, the test data, and wherever else the table is being used in the app.

**Comment by Boorclark** [comment]
This issue was fixed with PR 300 and it has been merged. Closing issue. Profile issue is being addressed in another issue and pr.
