### ISSUE TITLE
Create All Volunteer Training UI Change 

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#303]
On the Create All Volunteer Training page: remove all of the selector UI.
Path: _eventTemplates/2/create_

![image](https://user-images.githubusercontent.com/26262045/174311526-c6952839-ca5e-4fc1-8338-9939dbfdf9ec.png)
![image](https://user-images.githubusercontent.com/26262045/174311867-1bdac9c5-1fa5-4714-b3bd-c06094e9e961.png)

**Comment by Boorclark** [comment]
Mostaphe completed this issue and it got merged into development but forgot to link the issue to PR. Closing issue.
