### ISSUE TITLE
Fix text alignment in Volunteer Ban UI 

### ISSUE THREAD

**Issue by BrianRamsay** [BCStudentSoftwareDevTeam/celts#318]
The text in each row of the Volunteer Ban UI should be aligned vertically, and it is not. The Edit link doesn't match.

![alignment-issue](https://user-images.githubusercontent.com/96464/175563660-3826eb2d-6c2b-4751-b1d8-a67d1340e15b.png)

**Comment by bledsoef** [comment]
Pull request merged.
