### ISSUE TITLE
Add edit button to Service Learning course proposal 

### ISSUE THREAD

**Issue by gahimbaref** [BCStudentSoftwareDevTeam/celts#324]
There needs to be an edit button for admins in the  page that links to the appropriate edit page for that proposal (serviceLearning/editProposal/<courseID>).
![Untitled](https://user-images.githubusercontent.com/46611704/175983168-0b7abf46-8553-4a80-bac3-313620d27fd6.png)

**Comment by Boorclark** [comment]
This issue was fixed with PR 325 and it has been merged. Closing issue.
