### ISSUE TITLE
Refactor program manager permissions

### ISSUE THREAD

**Issue by BrianRamsay** [BCStudentSoftwareDevTeam/celts#326]
We should move our program manager permission functions into methods of the User object.

So instead of calling `hasPrivilege(user, program)`, we would call `user.hasPrivilege(program)`. Same with `isProgramManagerForEvent`.

We should also rename `hasPrivilege`. We can make it more clear by calling it `isProgramManagerFor` or `canManageProgram`

**Comment by Boorclark** [comment]
PR merged closing issue
