### ISSUE TITLE
Email Attachments 

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#337]
In _emailHandler.py_:
Complete the _attach_attachments_ function. 
![image](https://user-images.githubusercontent.com/26262045/176255036-28df8f66-84be-4ece-bbfb-11d5294a57c9.png)

**Comment by Boorclark** [comment]
Notes:
- Add "Add File" section to the Email Template HTML --> https://getbootstrap.com/docs/4.6/components/input-group/#custom-file-input
- We don't want to store it as a blob (maybeee) and instead want to save it to the database and access it via the "server directory."
- Look into how images are stored in a DB and what a model would look like
- Link for information on storing images in a file system --> https://softwareengineering.stackexchange.com/questions/164905/
how-best-to-store-images-on-a-file-system
