### ISSUE TITLE
Footer breaks on small screen sizes

### ISSUE THREAD

**Issue by romano-w** [BCStudentSoftwareDevTeam/celts#34]
The footer text breaks into a new line on smaller screen sizes because it is too wide. This breaks the layout because the footer uses a fixed height and the text is vertically centered by having a high line height.

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #34: Footer breaks on small screen sizes](https://trello.com/c/coM5HmhV/279-celts-34-footer-breaks-on-small-screen-sizes)
