### ISSUE TITLE
Add flash message for "Invalid User Search"

### ISSUE THREAD

**Issue by Boorclark** [BCStudentSoftwareDevTeam/celts#340]
Currently on the volunteer search page, if you search for a user that does not exist it will redirect you to a page saying "user does not exist". We will want this to go away and instead be replaced with a flash message that says "User does not exist." 
![image](https://user-images.githubusercontent.com/97637517/176260075-53421ac6-6d10-45d8-8dff-41ce53fc53be.png)

**Comment by nartehi** [comment]
This issue has been resolved.
