### ISSUE TITLE
Edit Service Learning Course duplicates data

### ISSUE THREAD

**Issue by Lyisus** [BCStudentSoftwareDevTeam/celts#342]
In the edit Service Learning Course proposal interface, if somebody submits edits, waits until the page refreshes, then goes back to the previous page, clicks on the previous button, and submits again will cause for data to be duplicated in the database, primarily entries in the courseinstructor table. This issue needs some more investigating to prevent the data duplication.

**Comment by Boorclark** [comment]
PR merged closing issue
