### ISSUE TITLE
Course Instructor for new Service Learning Course Proposal

### ISSUE THREAD

**Issue by gahimbaref** [BCStudentSoftwareDevTeam/celts#344]
In the Service Learning Course Proposals edit or create page, when you create a new course proposal and search for a course instructor, the name of the instructor shows up. However, if you use the arrow down key to select the instructor, all of their info shows up in the text field.

![image](https://user-images.githubusercontent.com/89202583/176453191-2a2d11ff-924a-4e13-98dc-b8e298483a7a.png)

**Comment by bledsoef** [comment]
PR merged, closing issue.
