### ISSUE TITLE
Different phone number formats in volunteer table

### ISSUE THREAD

**Issue by martinj2-dot** [BCStudentSoftwareDevTeam/celts#351]
![image](https://user-images.githubusercontent.com/54441608/176761782-6a287ef9-5afa-4d00-84e1-0d3784820f8b.png)

When adding users to the track volunteers table users have different phone number formats displayed on the webpage.  likely an issue regarding how the data is being stored in the user table.

![image](https://user-images.githubusercontent.com/54441608/176768131-1bbbecf4-da26-4125-9b3c-dc9e6ad14514.png)

File Path:  app/templates/trackVolunteers.html

URL: eventsList/"eventId"/track_volunteers

**Comment by Boorclark** [comment]
This issue won't matter once we have access to AD. AD doesn't store user phone numbers so we will have to access them through DUO I believe. I called IS&S and they stated that DUO formats phone numbers the same way for everyone. I would close this issue but @martinj2-dot  got very attached so @BrianRamsay if you believe that this is no longer an issue, could you do the inevitable and close this?
