### ISSUE TITLE
Unable to switch user off of ramsayb2

### ISSUE THREAD

**Issue by bledsoef** [BCStudentSoftwareDevTeam/celts#360]
No matter which user you choose you are unable to switch to any user but ramsayb2 which prevents issues from getting done because you can't view any other pages not as an admin.
![Annotation 2022-07-04 141454](https://user-images.githubusercontent.com/89262886/177202841-f3927594-7f95-4cf4-b3b4-9317db94c385.png)

**Comment by Boorclark** [comment]
Finn and I both had this issue earlier but now mine is working suddenly and Finn's is still broken. This will be a bug that we will have to address in person.

**Comment by bledsoef** [comment]
Garrett's fixed itself and mine was broken for another day without fixing itself, if this issue is had in the future I would suggest clearing cookies.
