### ISSUE TITLE
Event Creation Time Picker

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#366]
When the user is selecting a start and end time while creating an event they have to click on the clock in the right hand side of box to get the  time drop down menu. The drop down should appear when the user clicks anywhere in the box.

**Comment by Boorclark** [comment]
I don't believe this issue is fixable. The bootstrap documentation for the time picker default is unclickable on the box. https://mdbootstrap.com/docs/b4/jquery/forms/time-picker1/
@Andersonstettner @BrianRamsay

**Comment by Boorclark** [comment]
This is no longer an issue we are concerned about. Closing issue
