### ISSUE TITLE
Make events only able to be created in terms that are in the current academic year

### ISSUE THREAD

**Issue by bledsoef** [BCStudentSoftwareDevTeam/celts#368]
Currently, you can make an event in the Spring 2020 term that starts in July of 2030, this makes no sense. We need to make sure that events cannot be created outside of the currently selected terms academic year. For instance, the currently selected term could be the fall of 2022 and an event could be created spring of 2023 without a problem, but if the event is created outside of the academic year, like spring of 2025, it would request a new input.

**Comment by bledsoef** [comment]
Also make sure the default selected term is the current term.

**Comment by BrianRamsay** [comment]
We discussed this issue with them in the last meeting, and we are not restricting dates based on the term selected.
