### ISSUE TITLE
Allow multiple file uploads for events and email attachments

### ISSUE THREAD

**Issue by BrianRamsay** [BCStudentSoftwareDevTeam/celts#383]
Users should be allowed to attach multiple files to events and emails. We should also implement a little bit more validation over the files themselves (don't worry about file contents validation). See: https://blog.miguelgrinberg.com/post/handling-file-uploads-with-flask

**Comment by martinj2-dot** [comment]
By file validation do you mean choose what types of files we are allowing users to upload using accept?

**Comment by martinj2-dot** [comment]
Relevant file paths:

controllers/events/routes.py
templates/emailModal.html

Notes: 
"multiple" attribute allows multiple files to be sent, need to fix controller to handle multiple files.

**Comment by bledsoef** [comment]
PR's merged, closing issue.
