### ISSUE TITLE
Fast Clicking "Ban Volunteer" Creates Duplicate Data

### ISSUE THREAD

**Issue by Lyisus** [BCStudentSoftwareDevTeam/celts#388]
While banning a user in the Volunteer Profile, fast clicking on the "Ban Volunteer" button creates multiple entries on both the programban table and in the admin logs. Ideally, we can stop the process from happening on every click or preventing the user from clicking the button more than once. The same is true for the "Unban Volunteer" in the same interface.

**Comment by bledsoef** [comment]
PR merged, closing issue.
