### ISSUE TITLE
In the Service Learning Course Proposal: take out the hyphen in Service-Learning everywhere it appears, Improve the name of the page "New Designated Service-Learning Course", and fix both of the "service learning course guidelines" links

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#398]
Link 1:
![image](https://user-images.githubusercontent.com/26262045/178003349-57db6cf9-1db8-47c6-a492-5ac6527bdf83.png)

Link 2 and title to be changed:
![image](https://user-images.githubusercontent.com/26262045/178003392-df868157-4948-4a3f-84d1-541e51653244.png)

**Comment by bledsoef** [comment]
PR merged, closing issue.
