### ISSUE TITLE
Add File Upload To Event Creation

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#40]
We need a place for CELTS admins to be able to drag and drop and upload files when creating/editing an event.  The file(s) uploaded should be viewable on volunteer view after upload.

![image](https://user-images.githubusercontent.com/28715731/125121447-f2b21880-e0c1-11eb-8fb0-e7edbefe7bf7.png)
![image](https://user-images.githubusercontent.com/28715731/125121515-09f10600-e0c2-11eb-8001-34100b6fc1dd.png)

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #40: Add File Upload To Event Creation](https://trello.com/c/EzKDiapl/349-celts-40-add-file-upload-to-event-creation)

**Comment by Boorclark** [comment]
This issue should be addressed once issue #383 is completed and merged into development.
