### ISSUE TITLE
On the My Profile page on the Upcoming Events tab: display the users upcoming events and make it clear that the "Choose interests below..." header is related to the table. 

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#408]
![Annotation 2022-07-08 111519](https://user-images.githubusercontent.com/26262045/178021081-c557306f-fe18-4a75-91bc-9b0099bccb04.png)
At the top of the page the events that the user is going to be participating in should be displayed. If there are none the user should be told this.

Also the "Choose interests below..." header should be more clearly related to the table it is about.

**Comment by bledsoef** [comment]
The code in the html works fine, I think the query is messed up in logic because it is never printing any upcoming events.
