### ISSUE TITLE
Clean up createSingleEvent and remove all of the code that allows someone to just view it.

### ISSUE THREAD

**Issue by bledsoef** [BCStudentSoftwareDevTeam/celts#442]
There are certain instances right now where if someone clicks on an event it takes them to the old "view event" page which was just an altered edit event page. This is bad, get rid of it, please.

The new view event page is currently under construction, this will be on hold until issue #389 is resolved and PR #421 is merged. 
![Annotation 2022-07-12 100204](https://user-images.githubusercontent.com/89262886/178508461-175569a7-0a03-414a-aa8b-693df04f8a87.png)

Along with the changes to createSingleEvent, we will be adding a tab to admin and program manager view that will allow them to view the event, we're also going to change createSingleEvent to createEvent.

Controller should deny student staff access to edit if they aren't program managers.

**Comment by bledsoef** [comment]
Along with the changes to createSingleEvent, we will be adding a tab to admin and program manager view that will allow them to view the event, we're also going to change createSingleEvent to createEvent.

**Comment by bledsoef** [comment]
Controller should deny student staff access to edit if they aren't program managers.

**Comment by Boorclark** [comment]
Closing issue
