### ISSUE TITLE
Add functionality to allow multiple volunteers to be added at once.

### ISSUE THREAD

**Issue by martinj2-dot** [BCStudentSoftwareDevTeam/celts#445]
Add volunteer modal only allows user to add one volunteer at a time when form submits. Fix it to where you can add multiple volunteers at once.

![image](https://user-images.githubusercontent.com/54441608/178514449-bf15df05-8eb4-49b5-8a2d-a92c263f695c.png)

file paths:

app/templates/events/trackVolunteers.html

**Comment by bledsoef** [comment]
PR merged, closing issue
