### ISSUE TITLE
On My Profile page: make program names into links

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#446]
The program names on the interest table should be links to that event on the CELTS website so the user is able to get more information about the events.
![Annotation 2022-07-12 103912](https://user-images.githubusercontent.com/26262045/178516795-891f74d1-9252-4203-b554-1f0f5077bdd5.png)

**Comment by Boorclark** [comment]
The issue has been merged. Closing issue
