### ISSUE TITLE
In the Program Settings of the admin settings: remove drop down and just have a list of programs. Make the program names editable.

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#454]
![image](https://user-images.githubusercontent.com/26262045/178783136-9c3a654c-bcfb-47c4-b5ff-e073a2350c0e.png)
Instead of "Program Select" it should be a list of the program names that the user is able to update.

**Comment by bledsoef** [comment]
PR merged, closing issue.
