### ISSUE TITLE
instructor Duplicate in course instructor tabel 

### ISSUE THREAD

**Issue by qasema** [BCStudentSoftwareDevTeam/celts#472]
When creating or updating a new SL course proposal and adding the same instructor multiple times. it creates multiple instructor entries for the same course in the course instructor table.

<img width="1068" alt="Screen Shot 2022-07-14 at 10 37 29 AM" src="https://user-images.githubusercontent.com/68142980/179008475-cdd81f15-6d4b-4a93-997d-293f1aff2712.png">

**Comment by bledsoef** [comment]
PR merged, closing.
