### ISSUE TITLE
When faculty save and approve a proposal it brings them to a permission denied page

### ISSUE THREAD

**Issue by bledsoef** [BCStudentSoftwareDevTeam/celts#494]
![image](https://user-images.githubusercontent.com/89262886/179781459-cf769c7e-5759-4da1-a397-0f07e9a79ae7.png)
When a faculty saves a proposal it routes them back to the Service Learning page which they do not have access to, either we should always route a user back to their personal SL Proposal page or check if they are faculty and direct them back to that page.

**Comment by Boorclark** [comment]
PR merged closing issue
