### ISSUE TITLE
User Management Page can Give Admin Priviledges to Anyone

### ISSUE THREAD

**Issue by Lyisus** [BCStudentSoftwareDevTeam/celts#495]
In the User Managament or Admin Management page, users who know the username of a user in the database can type it and submit it, which will give that user the appropriate priviledges.
For example: this allow to give students Celts Admin priviledges, despite not showing up in the search bar.
![Untitled](https://user-images.githubusercontent.com/46611704/179787771-905dd2ef-ba2b-4fb9-a325-9da66a6b305d.png)

**Comment by bledsoef** [comment]
PR merged, closing issue.
