### ISSUE TITLE
Datetime Warning Issue Displayed On Volunteer Profile

### ISSUE THREAD

**Issue by Boorclark** [BCStudentSoftwareDevTeam/celts#549]
The following warning is displayed when viewing the "Volunteer Profile"/"My Profile" page in the console:
![image](https://user-images.githubusercontent.com/97637517/180293116-66aa8d12-0031-414c-86c9-592e1e79951f.png)
![image](https://user-images.githubusercontent.com/97637517/180293207-4bc669b1-11af-4498-9871-c9139fa66b86.png)

**Comment by bledsoef** [comment]
PR merged, closing issue
