### ISSUE TITLE
Save Button In Track Volunteers is Uneeded

### ISSUE THREAD

**Issue by Boorclark** [BCStudentSoftwareDevTeam/celts#561]
The save button in track volunteers is not needed because it should save when you add someone.
![image](https://user-images.githubusercontent.com/97637517/180462053-33ba913e-090e-4fb9-b6c4-bfd289bdb426.png)

**Comment by Ayushrawat-cmd** [comment]
@Boorclark Hey, so u just want to remove the html code of this button or something else..

**Comment by Boorclark** [comment]
The save button is needed for hours. Closing issue
