### ISSUE TITLE
Improve Id Usage

### ISSUE THREAD

**Issue by zachneill** [BCStudentSoftwareDevTeam/celts#564]
There is some Bootstrap 5 default code in development. E.g. id="myTable" in reviewproposal.html and manageServiceLearningFaculty.html, and id="exampleModalLabel" in trackVolunteers.html. I'd find new names for these and any other code that was ctrl+C-->ctrl+V'd from the [BS5 docs](https://getbootstrap.com/docs/5.0/getting-started/introduction/). 

Additionally, id="eventLength" and id="eventID" are used twice in trackVolunteers.html. ids should always be used once, so I'd refactor one or the other. 

Closed PR #490 may help.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve Id Usage #564](https://trello.com/c/cDs9GSJ6/430-improve-id-usage-564)

**Comment by Mercy-Eze** [comment]
Issue closed on #939
