### ISSUE TITLE
If event has passed or is currently happening for a given day, indicate that

### ISSUE THREAD

**Issue by bledsoef** [BCStudentSoftwareDevTeam/celts#571]
If event has happened or is currently happening for a given day on the upcoming section on my profile, indicate that with either a red bolding or some other visual cue.

**Comment by Lyisus** [comment]
Waiting on issue #591 to be completed before finishing this.

**Comment by Lyisus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Distinguishes between events happening now, later today and upcoming events](https://trello.com/c/Y2ceP9aK/437-distinguishes-between-events-happening-now-later-today-and-upcoming-events)
