### ISSUE TITLE
Rework My Profile page

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#591]
Refactor the My Profile page. 

- Remove the two tabs at the top of the page.
- Have an Upcoming Events header and put the upcoming events under it
- Put a link to their Service Transcript on the top right of the page 
- The "Choose interests below..." should be a header to the table and it should always be there regardless of weather or not they have any upcoming events being displayed

![My Profile ](https://user-images.githubusercontent.com/26262045/180805956-4dc9a748-b38c-4e18-9a0d-5199a8e51c34.png)

**Comment by Boorclark** [comment]
PR merged. Closing issue
