### ISSUE TITLE
Approved SL Course interaction 

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#618]
Currently, if a course is approved the admin looses the ability to interact with it. We want them to be able to still have the ability to view the approved courses and request changes/un-approve the proposal which will push it back to the incomplete status.

**Comment by Boorclark** [comment]
This PR is linked to #582. Went ahead and assigned Ala to those because they encompass each other.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Approved SLC interaction #618](https://trello.com/c/9KprCe2I/405-approved-slc-interaction-618)
