### ISSUE TITLE
Adding Volunteer should also add hours

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#622]
Currently, if a volunteer is added to an event it only adds that volunteer, and not their hours, when they are put in the table. For the hours to also be added in the user has to hit the save button on the table. We want the hours to be added in when the user is added to the table.

**Comment by BrianRamsay** [comment]
This might end up being a little more complicated if we are needing to distinguish between EventRsvp and EventParticipant. We only want to record the hours if they are being recorded as a participant (if we are adding on the same day or after an event)

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Adding Volunteer with their hours #622](https://trello.com/c/g3u99aXv/404-adding-volunteer-with-their-hours-622)
