### ISSUE TITLE
Bonner training events should not show up for normal students

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#637]
Currently if a Bonner event is created as a training it will show up in the Training and Education tab for everyone. The Bonner trainings should have the same permissions to view as other Bonner events.

**Comment by Lyisus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bonner Training events should not show up for non-Bonner students #637](https://trello.com/c/MpfSRdHg/436-bonner-training-events-should-not-show-up-for-non-bonner-students-637)
