### ISSUE TITLE
Add Volunteer full username functionality

### ISSUE THREAD

**Issue by Boorclark** [BCStudentSoftwareDevTeam/celts#639]
When adding a volunteer, if you type in the full username of the user you are trying to add, you are not able to click enter and you have to backspace one to be able to submit on their popup.
![image](https://user-images.githubusercontent.com/97637517/182671680-059b46d0-bdc5-4039-8d8a-f26438933ad0.png)
![image](https://user-images.githubusercontent.com/97637517/182672414-af237fb4-f1ec-4377-be2f-de630c830f0d.png)

**Comment by bledsoef** [comment]
PR merged, closing issue.
