### ISSUE TITLE
"Send to Registrar" functionality and rename 

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#643]
Should be renamed to something like "Send SLC Recommendation" or "Send Recommendation".

Send a list by email of our Approved courses for the term, with all of their relevant data to a group of reviewers + the registrar. Should probably be sent as an Excel file. Also who are the reviewers we are sending to?

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ["Send to Registrar" functionality and rename #643](https://trello.com/c/YJ0WNZLz/442-send-to-registrar-functionality-and-rename-643)

**Comment by Karina-Agliullova** [comment]
What exactly is meant by relevant data? Is it only the information on the Course Proposals page? Or is it also the information used when creating those course proposals?


List of relevant info: -> export as excel OR take the email and populate it with relevant info as a text
course name
code for the course
faculty
Designate the newly designated course vs returning course
