### ISSUE TITLE
Empty values should not put 'None'  input boxes. #651

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#651]
Fix all nullable input fields to be empty instead of ‘None’

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Empty values should not put 'None' input boxes. #651](https://trello.com/c/K6NwyJoo/449-empty-values-should-not-put-none-input-boxes-651)

**Comment by sreynit02** [comment]
No Longer an issue
