### ISSUE TITLE
Add visible notification when adding and removing a program manager

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#654]

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add visible notification when adding and removing a program manager #654](https://trello.com/c/r1hyJDb9/452-add-visible-notification-when-adding-and-removing-a-program-manager-654)

**Comment by gastonjarju** [comment]
Issue has been resolved.
