### ISSUE TITLE
Banned Volunteer permissions 

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#657]
Banned volunteers should:

- NOT see upcoming events when they are banned from that program. They will still be able to see the program events on the Events List page but they will not appear as upcoming events on their Student Profile. 
- NOT be able to RSVP (pretty sure this is already done)

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Banned Volunteer permissions #657](https://trello.com/c/Sv7YE0f9/456-banned-volunteer-permissions-657)

**Comment by tylerpar99** [comment]
Finn and I began working on this issue, as we were working it became clear that we had to move background check out of volunteers and into user. If you are picking up this issue you will want to spot-check that importing this function from volunteer is changed to importing from user. Outside of that, we were also making a bannedprograms function that would return a list of programs a user was banned from so we could stop them from seeing events in those programs.
