### ISSUE TITLE
Selectively remove service transcript entry for banned programs

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#658]
Add a checkbox to the ban modal dialog to choose whether to completely remove the program from the service transcript (are they in Good Standing or not)

Make the checkbox actually affect the service transcript

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Selectively remove service transcript entry for banned programs #658](https://trello.com/c/1y7PJAEM/457-selectively-remove-service-transcript-entry-for-banned-programs-658)

**Comment by BrianRamsay** [comment]
Completed
