### ISSUE TITLE
The show upcoming events page currently has no styling.

### ISSUE THREAD

**Issue by Sandesh-L** [BCStudentSoftwareDevTeam/celts#67]
Add styles to the table and page

**Comment by Sandesh-L** [comment]
The branch name is `upcoming-events-table-forntend-67` The branch is created and stying is added but the buttons don't yet have functionalities.

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #67: The show upcoming events page currently has no styling.](https://trello.com/c/8gWDcdKb/289-celts-67-the-show-upcoming-events-page-currently-has-no-styling)

**Comment by bryantal** [comment]
This was fixed when the volunteer profile was combined in PR #87
