### ISSUE TITLE
My Profile is running too many queries

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#672]

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [My Profile is running too many queries #672](https://trello.com/c/srPgg22n/470-my-profile-is-running-too-many-queries-672)

**Comment by Andersonstettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add visible notification when adding and removing a program manager #654](https://trello.com/c/r1hyJDb9/452-add-visible-notification-when-adding-and-removing-a-program-manager-654)
