### ISSUE TITLE
Need Program on event page

### ISSUE THREAD

**Issue by BrianRamsay** [BCStudentSoftwareDevTeam/celts#680]
The program for an event is not visible on any of the event pages. We should display it, perhaps under the title. "A Berea Tutoring Event", "A CELTS-Sponsored Event", etc

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Need Program on event page #680](https://trello.com/c/NzYMOa8I/486-need-program-on-event-page-680)
