### ISSUE TITLE
Create Event Time picker does not work on mobile

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#690]
When a user tries to create an event on mobile they are not able to select a time for the event to occur due to the times not being selectable after the dropdown comes out.

The time picker is showing up behind the input elements. Reported on iOS

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Event Time picker does not work on mobile #690](https://trello.com/c/6xCZO3jc/490-create-event-time-picker-does-not-work-on-mobile-690)

**Comment by Mercy-Eze** [comment]
Issue does not exist at the moment

Resolved #690
