### ISSUE TITLE
Make CELTS sponsored events into a program 

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#691]
In order to handle permissions for events that don't have a program we need to change the "other" category to a "CELTS-Sponsored" program. This means all of the places that assume there are events with no program need to be altered.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make CELTS sponsored events into a program #691](https://trello.com/c/E9vAaAEI/492-make-celts-sponsored-events-into-a-program-691)

**Comment by Lyisus** [comment]
Working on this issue alongside issue #721
