### ISSUE TITLE
Increase the specificity of Admin Logs for events.

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#717]
Currently, the admin log for when an event is created/deleted only says the name of the event and its start date. We want to change that so it says, at least, what program the event belongs to and if it is a recurring event.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Increase the specificity of Admin Logs for events. #717](https://trello.com/c/OjpxLAX5/517-increase-the-specificity-of-admin-logs-for-events-717)

**Comment by Andersonstettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Increase the specificity of Admin Logs for events. #717](https://trello.com/c/OjpxLAX5/517-increase-the-specificity-of-admin-logs-for-events-717)
