### ISSUE TITLE
All Volunteer trainings should show up as required trainings for all programs.

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#721]
For now, we want All volunteer training to be required training for all programs but when you hover over the "view" training for programs it is not on all of them.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [All Volunteer trainings are not being added to all the programs correctly #721](https://trello.com/c/et6fKd8V/518-all-volunteer-trainings-are-not-being-added-to-all-the-programs-correctly-721)

**Comment by Lyisus** [comment]
Working on this issue alongside issue #691
