### ISSUE TITLE
Remove the "Invalid Date" in the Background Check history 

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#728]
Currently if the date is blank when a user tries to submit a background check ": Invalid Date" in put into its history. 

![image](https://user-images.githubusercontent.com/26262045/188676117-1687d479-b878-4687-b16d-b30f286594a8.png)

Lets not accept an input unless both fields have something in them and, instead of having a status message pop up over the save button if a field is not filled in, lets outline the box that is not filled in in red to show an input is required.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove the "Invalid Date" in the Background Check history #728](https://trello.com/c/4qa5rRdJ/523-remove-the-invalid-date-in-the-background-check-history-728)

**Comment by Andersonstettner** [comment]
Take away word messages and highlight empty fields if a save is attempted.
