### ISSUE TITLE
Track the Bonner requirements 

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#733]
Bonners are required to participate in a certain number events every year and they are also required to attend certain events every year. We want to allow Bonners and Admin to see progress on the requirement fulfillment and possibly show warnings if they are cutting it close to not meeting them.

The requirements and progress should be able to be seen on the Bonners student profile and from the Bonner management Admin page. (issue #732 for user profile and issue #734 for Admin page)

Sub-issue of #603 , #732, #734

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Track the Bonner requirements](https://trello.com/c/97UNFLoZ/528-track-the-bonner-requirements)

**Comment by BrianRamsay** [comment]
Preliminary list of Bonner events:
Bonner Orientation
All Bonner Meeting (I lied, this is something that happens every semester and would be required for everyone)
First Year Service Trip
Sophomore Exchange
Junior Recommitment
Senior Legacy Training
Senior Presentation of Learning
Bonner Congress (optional)
Bonner Student Leadership Institute (optional)

"And it would be nice to have the option to add another Bonner event just in case"
