### ISSUE TITLE
Refactor sendUserData and addPersonToEvent together into one function. 

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#746]
Currently in participants.py we have one function to add event participants when through kiosk (sendUserData) and another for adding event participants all other ways (addPersonToEvent). Combine them into one function.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor sendUserData and addPersonToEvent together into one function. #746](https://trello.com/c/G4K9uCTn/540-refactor-senduserdata-and-addpersontoevent-together-into-one-function-746)

**Comment by nartehi** [comment]
Refractored the two functions into one. 
We will need to test it to see if it works though
