### ISSUE TITLE
Increase the word limit in the event description and tell the user what that limit is. 

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#747]
The current the word limit is 255 (the default limit) and we want it increased to 350. We should also tell the user what the word limit is somewhere.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Increase the word limit in the event description and tell the user what that limit is. #747](https://trello.com/c/XoPaUFXD/539-increase-the-word-limit-in-the-event-description-and-tell-the-user-what-that-limit-is-747)

**Comment by BrianRamsay** [comment]
I have updated the column to be a TEXT field in production. Change still needs to be made to the model
