### ISSUE TITLE
Add the ability to limit the number of volunteers that can RSVP to an event. 

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#748]
Also, add a waitlist after RSVP limit has been reached.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add the ability to limit the number of volunteers to an event. #748](https://trello.com/c/HsFbG9aG/541-add-the-ability-to-limit-the-number-of-volunteers-to-an-event-748)

**Comment by Andersonstettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add a new Background check category: Student Life #749](https://trello.com/c/4U3spXI4/542-add-a-new-background-check-category-student-life-749)
