### ISSUE TITLE
Faculty Create Service Learning Course Proposals

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#76]
This issue covers SRS item 5.1 - The faculty must be able to create SL Course Proposals (From the [CELTS SRS](https://docs.google.com/document/d/17URsAbRVdhJ9lBABzlM3Zk7KKbmuD2m9aYMT3tG2lkw/edit))

The faculty will need to have functionality to create service learning course proposals through a page like this one:
![image](https://user-images.githubusercontent.com/28715731/129572685-9069bb2c-f9fc-4514-bbd3-f9724ed48684.png)

See Faculty UI Wireframe: https://balsamiq-wireframes.appspot.com/?state=%7B%22ids%22:%5B%221ziGyTzz6J7iHjyzmsUzj0yzvuFdITg3n%22%5D,%22action%22:%22open%22,%22userId%22:%22109665407847548855125%22,%22resourceKeys%22:%7B%7D%7D

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #76: Faculty Create Service Learning Course Proposals](https://trello.com/c/nnnVz7U1/274-celts-76-faculty-create-service-learning-course-proposals)

**Comment by MayJue** [comment]
https://docs.google.com/document/d/1asrfreFu6tcCQlXTd5XQ9SU5k7j5aCARAJQPjsAillY/edit

**Comment by zachneill** [comment]
What's the difference between issue #78 and pr #98 versus this one? The frontend for this was done, although only "view" works

**Comment by bryantal** [comment]
> What's the difference between issue #78 and pr #98 versus this one? The frontend for this was done, although only "view" works

This one will also include the interface for creating proposal from scratch, with all of the guidelines included.  The table will be the starter that the rest of the functionality hangs off of.  There are interfaces needed for each option in the dropdown.

**Comment by zachneill** [comment]
We can close #160 and close #165 since this pr integrates all the code from 165 and makes that pr obsolete
