### ISSUE TITLE
End Time is not checked when creating recurring events

### ISSUE THREAD

**Issue by sreynit02** [BCStudentSoftwareDevTeam/celts#768]
At the moment, when creating a recurring event, if the end time of the event is the same as the start time, the application does not ask the user to fill in a different time.

**Comment by Andersonstettner** [comment]
Example:
![image](https://user-images.githubusercontent.com/26262045/193613467-ef0127c5-4db3-4445-8684-e005dd11c3a0.png)
![image](https://user-images.githubusercontent.com/26262045/193613541-02b44875-9623-4974-8bd6-592b7b63856f.png)

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [End Time is not checked when creating recurring events #768](https://trello.com/c/0s7oG47P/586-end-time-is-not-checked-when-creating-recurring-events-768)
