### ISSUE TITLE
Fix the text encoding 

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#776]
We are not encoding text correctly so there are cases where text can be copied into a text box that has symbols that our database cant accept causing it to throw errors. 
![image](https://user-images.githubusercontent.com/26262045/194579089-d1a33211-adbb-4cca-aebb-563445d0f654.png)

**Comment by Andersonstettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix our text encoding #776](https://trello.com/c/ReeZZ4fB/565-fix-our-text-encoding-776)

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix the text encoding #776](https://trello.com/c/ReeZZ4fB/565-fix-the-text-encoding-776)
