### ISSUE TITLE
Fix Program Managers uploading pngs to events

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#786]
When Program Managers attempt to upload png posters to events they are thrown a "system error". Investigate where it is coming from and fix.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Program Managers uploading pngs to events #786](https://trello.com/c/idPCtYFe/568-fix-program-managers-uploading-pngs-to-events-786)

**Comment by martinj2-dot** [comment]
This was a known bug when Ala and I were creating the file upload feature. I knew it would come back to bite us. Will work on it.
