### ISSUE TITLE
Admin is not able to remove volunteers

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#789]
Sarah has been trying to remove volunteers to clean up past events but she is not able to.

I had a meeting with her where she brought this up so I tested it right fast and I was able to add and remove volunteers with no problem on both development and production without problems, though, Sarah suggested that it may have something to do with how the volunteers were added to an event so that might be a good place to start.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Admin is not able to remove volunteers #789](https://trello.com/c/pGjI1d2x/569-admin-is-not-able-to-remove-volunteers-789)

**Comment by martinj2-dot** [comment]
Maybe this would be a good issue for one of us to go out and meet Sarah so she can recreate the issue for us to see what's going on. There's not really enough information to go off of for us to work on this one.
