### ISSUE TITLE
Faculty Edit Service Learning Course Proposals

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#79]
Faculty UI Wireframe: https://balsamiq-wireframes.appspot.com/?state=%7B%22ids%22:%5B%221ziGyTzz6J7iHjyzmsUzj0yzvuFdITg3n%22%5D,%22action%22:%22open%22,%22userId%22:%22109665407847548855125%22,%22resourceKeys%22:%7B%7D%7D

The faculty must be able to edit service learning course proposals from the table where they view all of them.
SRS Item: **5.3** The faculty must be able to edit SL  Course Proposals
![image](https://user-images.githubusercontent.com/28715731/129770052-606a2c9b-0705-4706-ae0c-0d33d930e0e9.png)

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #79: Faculty Edit Service Learning Course Proposals](https://trello.com/c/9b572uA4/292-celts-79-faculty-edit-service-learning-course-proposals)

**Comment by mupotsal** [comment]
@zachneill  and @Sandesh-L what issue where you working on that is almost similar to this isssue?

**Comment by zachneill** [comment]
we made pr #98 which is the same page and has withdraw functionality. it was merged and the url is supposed to be /courseProposals. However, I can't seem to get it working while on the development branch.
