### ISSUE TITLE
Refactor programEvent table

### ISSUE THREAD

**Issue by gahimbaref** [BCStudentSoftwareDevTeam/celts#792]
Get rid of the programEvent table by replacing it with a program column in the event table
Change all the files that use the programEvent table to use the program column instead.

Once the refactoring has been completed, create a script that will change the database structure and all its contents from the one using the programEvent table to the one using the program column in the event table without losing any data. This script is to use in production to correctly update production's database without losing any data.

**Comment by gahimbaref** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor programEvent table #792](https://trello.com/c/7sFohKiP/571-refactor-programevent-table-792)

**Comment by Lyisus** [comment]
Expected Completion Date: November 18th 2022
Expected PR Completion Date: TBD
