### ISSUE TITLE
Upgrade Flask

### ISSUE THREAD

**Issue by martinj2-dot** [BCStudentSoftwareDevTeam/celts#799]
The current version of Flask running on CELTS is 2.0.1. 

The most up to date version is 2.2.2.

https://pypi.org/project/Flask/

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Upgrade Flask #799](https://trello.com/c/ghya89sX/587-upgrade-flask-799)
