### ISSUE TITLE
Faculty Delete Service Learning Course Proposals

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#80]
Faculty UI Wireframe: https://balsamiq-wireframes.appspot.com/?state=%7B%22ids%22:%5B%221ziGyTzz6J7iHjyzmsUzj0yzvuFdITg3n%22%5D,%22action%22:%22open%22,%22userId%22:%22109665407847548855125%22,%22resourceKeys%22:%7B%7D%7D

The faculty must be able to delete their service learning course proposals from the table where they view them all.  They can only delete service learning course proposals that have not been approved.
SRS Items: **5.4** The faculty must be able to delete SL Course Proposals
![image](https://user-images.githubusercontent.com/28715731/129770442-4ea9c604-b60a-4195-b1d3-05cffece3f46.png)

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #80: Faculty Delete Service Learning Course Proposals](https://trello.com/c/Z5tn5Jay/293-celts-80-faculty-delete-service-learning-course-proposals)

**Comment by mupotsal** [comment]
This issue has been solved in issue#78
