### ISSUE TITLE
Add Defensive driving

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#810]
CERT

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Defensive driving to the background check section. #810](https://trello.com/c/ljvg71yD/581-add-defensive-driving-to-the-background-check-section-810)

**Comment by nartehi** [comment]
Changed the background status options to those suggested by Anderson.
We need to find a way that volunteers can indicate if they passed the defensive driving.

**Comment by JohnCox2211** [comment]
Submitted PR for updated code, "Defensive Driving Background Check Option Added"
