### ISSUE TITLE
Add the ability to use kiosk mode form a mobile phone, use camera to capture barcode on IDs

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#812]

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add the ability to use kiosk mode form a mobile phone, use camera to capture barcode on IDs #812](https://trello.com/c/99d5seQZ/583-add-the-ability-to-use-kiosk-mode-form-a-mobile-phone-use-camera-to-capture-barcode-on-ids-812)

**Comment by doucoureb** [comment]
Barcode scanner successfully implemented using HTLM5qrcode library; quagga library previously used but was not accurately working.
There is a footer issue that needs to be fixed when the scanner is displayed
Also had some thoughts about adding a beep sound to the barcode
