### ISSUE TITLE
On Events list page only show current and future events to students and gray out past events for Admin and Student Staff

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#813]

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [On Events list page only show current and future events to students and gray out past events for Admin and Student Staff #813](https://trello.com/c/ArohxtxT/584-on-events-list-page-only-show-current-and-future-events-to-students-and-gray-out-past-events-for-admin-and-student-staff-813)

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 813 event list](https://trello.com/c/otizyOh5/607-issue-813-event-list)

**Comment by Mercy-Eze** [comment]
Solved on PR #835
