### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#82]
When running the application, a user needs a starting page to land on, so they can use the navbar to get around the application.  The landing page should be the all events page.
![image](https://user-images.githubusercontent.com/28715731/129915109-6e827734-ea5c-4f30-ba7d-e059225b13d8.png)

For volunteers, their profile page should be the landing page.
![image](https://user-images.githubusercontent.com/28715731/129920721-c527b9d5-dd85-410e-b1b5-c7a396d95d50.png)

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #82: Landing Page](https://trello.com/c/1rCW5pFH/287-celts-82-landing-page)

**Comment by hmanalai** [comment]
We decided to have the events page be the landing page for all users.
