### ISSUE TITLE
Create a "RSVP history" on the Track Volunteers page.

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#829]
Create another tab on events for RSVP History. This will display an RSVP log for that event and it should look something like the Admin log. We want to record ALL RSVP actions: 

- When an RSVP occurs
- When someone un RSVPs
- When someone is deleted from the RSVP table
- When someone is put on the waitlist
- When someone is delete from the waitlist table
- When someone is moved from the waitlist table to the RSVP table an who moved them
- When someone is added to the RSVP table through the "Add Volunteer" modal and who added them

Checkout `rsvpLog` branch to work on this issue. Talk with Anderson when starting.

**Comment by gahimbaref** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create a "RSVP history" on the Track Volunteers page. #829](https://trello.com/c/v9uHWkw2/594-create-a-rsvp-history-on-the-track-volunteers-page-829)
