### ISSUE TITLE
Navbar Routes

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#83]
For admins, The all events page and the student search page need to be accessible from the navbar.  For students, their volunteer profile page and the all events page need to be accessible from the navbar.

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #83: Navbar Routes](https://trello.com/c/oqFYaM4K/294-celts-83-navbar-routes)

**Comment by sreynit02** [comment]
resolved by PR #90
