### ISSUE TITLE
Change wording/messaging for SLC statuses.

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#832]
Some of the feedback given is that our messaging about a courses status is confusing, especially the "Incomplete" status. Change "Incomplete" to "In Progress" and think about other possible changes that could be made.

**Comment by bledsoef** [comment]
Being addressed in PR #822

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change wording/messaging for SLC statuses. #832](https://trello.com/c/lgRmlPvZ/597-change-wording-messaging-for-slc-statuses-832)
