### ISSUE TITLE
Consolidate student search methods

### ISSUE THREAD

**Issue by BrianRamsay** [BCStudentSoftwareDevTeam/celts#84]
There are multiple routes and functions that handle searching for students.
`app/logic/searchVolunteers.py`, `app/logic/searchStudents.py`, and ` searchVolunteers() in app/controllers/admin/routes.py` all have a different implementation.

We need to consolidate to a single search method. multiple routes are ok, as long as they are for different purposes and handled by (probably) one controller method.

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #84: Consolidate student search methods](https://trello.com/c/Cp2VNHWg/298-celts-84-consolidate-student-search-methods)
