### ISSUE TITLE
Generalize Spreadsheet queries and write tests for them

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#884]
There is a logic file, `spreadsheet.py`, that queries the database for data that CELTS has asked for. The three main tasks for this issue are to generalize the functions, write tests for the new logic file, and create UI to download the data within the application. 

### Task one:
Currently, a few of the queries are too specific, the terms for getting retention rates are the main ones I can think of. Using the retention rate as an example, we want to allow the user to select which terms they would like to be used to calculate the retention rate instead of hardcoding them in the logic like they are now. 

### Task two: 
Write new tests for the new `spreadsheet.py` logic.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Generalize Spreadsheet queries and create UI for it in the application #884](https://trello.com/c/uZEbZj1f/610-generalize-spreadsheet-queries-and-create-ui-for-it-in-the-application-884)

**Comment by solijonovam** [comment]
We created tests for spreadsheet.py, should we create another issue for  creating UI to download the data?
