### ISSUE TITLE
Move the `Close` button on the renew modal to the left side 

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#887]
We have "Close", "Exit", and "Delete" buttons on the left side of modals across the application so we should move this one over as well to keep it consistent.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Move the "Close" button on the renew modal to the left side #887](https://trello.com/c/l8AG6gji/612-move-the-close-button-on-the-renew-modal-to-the-left-side-887)

**Comment by Andersonstettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change SLC Question char count to word count and improve their look #888](https://trello.com/c/OriG4gTi/613-change-slc-question-char-count-to-word-count-and-improve-their-look-888)
