### ISSUE TITLE
Change the wording of the "Submit" button for SLC Proposals

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#889]
Change "Submit" to something like "Submit Proposal"

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change the wording of the "Submit" button for SLC Proposals #889](https://trello.com/c/dEqhnz5a/614-change-the-wording-of-the-submit-button-for-slc-proposals-889)

**Comment by Andersonstettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix dropdowns needing a page reload to select the same option #890](https://trello.com/c/azORmfwK/615-fix-dropdowns-needing-a-page-reload-to-select-the-same-option-890)
