### ISSUE TITLE
Volunteer Upcoming Events Link to Event

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#89]
There needs to be a way for the volunteer to view the event page for events in the upcoming events.  Being able to click on the event name on the table and it lead the user to the volunteer view of the event page would be best.
![image](https://user-images.githubusercontent.com/28715731/130466683-0e615982-6a76-4c14-8204-ea38643f098c.png)

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #89: Volunteer Upcoming Events Link to Event](https://trello.com/c/dBXPmeeq/296-celts-89-volunteer-upcoming-events-link-to-event)

**Comment by mupotsal** [comment]
Sandesh is working on making the page first. Links will be added after the page is created. 

https://github.com/BCStudentSoftwareDevTeam/celts/issues/67

**Comment by zachneill** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #89: Volunteer Upcoming Events Link to Event](https://trello.com/c/Q0oT1IYg/302-celts-89-volunteer-upcoming-events-link-to-event)
