### ISSUE TITLE
Set `Send Recommendation` and `Email All` buttons target to _blank

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#892]
On the Admin Course Management page, set the `Send Recommendation` and `Email All`  buttons target = "_blank"

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Set Send Recommendation and Email All buttons target to _blank #892](https://trello.com/c/a3ULV2WM/617-set-send-recommendation-and-email-all-buttons-target-to-blank-892)

**Comment by Andersonstettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rename Download File button to Download Course List on Admin Course Management page #893](https://trello.com/c/axTZ8EMo/618-rename-download-file-button-to-download-course-list-on-admin-course-management-page-893)
