### ISSUE TITLE
Rename `Download File` button to `Download Course List` on Admin Course Management page

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#893]

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rename Download File button to Download Course List on Admin Course Management page #893](https://trello.com/c/axTZ8EMo/618-rename-download-file-button-to-download-course-list-on-admin-course-management-page-893)

**Comment by ananyabhat29** [comment]
Hey @Andersonstettner 
Can I take this up?

**Comment by AndersonStettner** [comment]
> Hey @Andersonstettner Can I take this up?

Yeah, feel free to.

**Comment by chandansgowda** [comment]
@ananyabhat29 You can find the button here [Check This](https://github.com/BCStudentSoftwareDevTeam/celts/blob/45eb760ffe498f19a4ecb753cffa2148411a5a35/app/templates/main/manageServiceLearningFaculty.html#LL110C7-L110C7)
Please correct me if I'm wrong @Andersonstettner
