### ISSUE TITLE
Faculty Service Learning Course Management

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#9]
This will be a part of the Service Learning Course Management UI

This is where a faculty will be able to view all of their service learning course requests (5.1-5.5 on CELTS SRS: https://docs.google.com/document/d/17URsAbRVdhJ9lBABzlM3Zk7KKbmuD2m9aYMT3tG2lkw/edit)

See Faculty UI Wireframe: https://balsamiq-wireframes.appspot.com/?state=%7B%22ids%22:%5B%221ziGyTzz6J7iHjyzmsUzj0yzvuFdITg3n%22%5D,%22action%22:%22open%22,%22userId%22:%22109665407847548855125%22,%22resourceKeys%22:%7B%7D%7D

The slide titled "5.2 - Faculty Proposal View" is what we want this page to look like.
![image](https://user-images.githubusercontent.com/28715731/121893123-9c80ce00-cceb-11eb-9bd4-7d169ec8db3d.png)

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #9: Faculty Service Learning Course Management](https://trello.com/c/nnnVz7U1/274-celts-9-faculty-service-learning-course-management)

**Comment by Boorclark** [comment]
This issue has been fully resolved. Closing issue
