### ISSUE TITLE
Update the CELTS Logo for the printed SLC Proposal. 

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#900]
The logo on the top of the printed SLC Proposal is the old one, replace it with the new one. The new logo is the one we have displayed on the top left of the sidebar.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update the CELTS Logo for the printed SLC Proposal. #900](https://trello.com/c/miHobK59/625-update-the-celts-logo-for-the-printed-slc-proposal-900)

**Comment by Andersonstettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hide all other visibility options when creating notes if "Related to Bonner..." is checked #901](https://trello.com/c/TEfahxW8/626-hide-all-other-visibility-options-when-creating-notes-if-related-to-bonner-is-checked-901)
