### ISSUE TITLE
Refactor Event page navigation tabs

### ISSUE THREAD

**Issue by BrianRamsay** [BCStudentSoftwareDevTeam/celts#943]
The navigation tabs on the event page (/eventsList/12/view) are currently duplicated across different templates for each tab. We should create a template for the event page that includes the title and the navigation and then includes the appropriate template for the active tab.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor Event page navigation tabs #943](https://trello.com/c/ea4Zp0GE/638-refactor-event-page-navigation-tabs-943)
