### ISSUE TITLE
Refactor Track Volunteers controller and template

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#944]
Refactor the controller (`/eventsList/<eventID>/track_volunteers`) to simplify the data controller gets and the template needs.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor Track Volunteers controller and template #944](https://trello.com/c/z4UURNhs/637-refactor-track-volunteers-controller-and-template-944)

**Comment by daizenj** [comment]
Request for more Info/Update: Couldn't locate route` /eventsList/<eventID>/track_volunteers` either this has already been refactored or it no longer exists. Please provide more information or update the issue if there have been changes.
