### ISSUE TITLE
Delete Event Not Redirecting

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/celts#95]
When in the event creation interface, the delete event button does not redirect correctly.  It should redirect back to the event management page that shows all of the events
![image](https://user-images.githubusercontent.com/28715731/131025852-bbf4cef8-48a3-4ae4-a3bc-6d54f17c0df4.png)

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CELTS #95: Delete Event Not Redirecting](https://trello.com/c/lkEaB5XJ/300-celts-95-delete-event-not-redirecting)

**Comment by hmanalai** [comment]
The cancel button is deleting the event. @BrianRamsay @bryantal  Is that the correct behavior?
