### ISSUE TITLE
Student staff retain their program management roles on events even after being removed as student staff

### ISSUE THREAD

**Issue by hoerstl** [BCStudentSoftwareDevTeam/celts#957]
When you are listed as a student manager and you have been searched by an admin under the student search sidebar item, a special accordion item appears that allows you to add and remove a student manager as a `program manager` for each event that is available. If you log in as an admin and click the dropdown for administrators, in admin/settings/User Management you have the ability to revoke the status of student managers. 

Currently, when you revoke the student manager status from a student, it doesn't take away their program manager status in the database for all of the programs that they were managers for. This creates an unclean database. When we remove an admin we should also go to each of the programs that they were managers for and then remove them as a program manager.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Student staff retain their program management roles on events even after being removed as student staff #957](https://trello.com/c/TYjpBQZY/640-student-staff-retain-their-program-management-roles-on-events-even-after-being-removed-as-student-staff-957)
