### ISSUE TITLE
Clean up empty directories for file attachments on recurring events.

### ISSUE THREAD

**Issue by ojmakinde** [BCStudentSoftwareDevTeam/celts#972]
Currently, when handling attachments for recurring events, separate directories are being created for each recurring event, even though all recurring events reference the same directory in memory. To improve efficiency and prevent unnecessary directory creation, modify the file saving process so that directories are not created for each recurring event after the first one. This will help improve file organization.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Clean up empty directories for file attachments on recurring events. #972](https://trello.com/c/2MZBaj2L/642-clean-up-empty-directories-for-file-attachments-on-recurring-events-972)

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Clean up empty directories for file attachments on recurring events. #972](https://trello.com/c/2MZBaj2L/642-clean-up-empty-directories-for-file-attachments-on-recurring-events-972)
