### ISSUE TITLE
Editing a recurring event removes it's recurring link

### ISSUE THREAD

**Issue by BrianRamsay** [BCStudentSoftwareDevTeam/celts#974]
The link between recurring events is removed when you edit a recurring event. Something is updating the recurring id improperly

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Editing a recurring event removes it's recurring link #974](https://trello.com/c/JU13O0CK/643-editing-a-recurring-event-removes-its-recurring-link-974)

**Comment by michelmonc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Editing a recurring event removes it's recurring link #974](https://trello.com/c/JU13O0CK/643-editing-a-recurring-event-removes-its-recurring-link-974)
