### ISSUE TITLE
Test email functionalities

### ISSUE THREAD

**Issue by hoerstl** [BCStudentSoftwareDevTeam/celts#976]
We are currently skipping 5 tests that test our email validations. We don't want to skip them and we should figure out how the validation works and reenable those tests and the email functionality.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test email functionalities #976](https://trello.com/c/daBeZdPI/644-test-email-functionalities-976)
