### ISSUE TITLE
Create Student CCE Minor page 

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#989]
Controllers: 
`/profile/<username>/cceMinor`, `/cceMinor/<username>/addSummerExperience`, and `/cceMinor/<username>/indicateInterest`

Balsamiq: https://drive.google.com/file/d/1X8v6z63RKa56WTyIyNLx3LX_kaz7l6Pr/view?usp=share_link

## Student Minor Page:
A student should NOT have the ability to edit anything on this page aside from the interest check. 
Each section (Sustained Community Engagement and Community-Engaged Summer Experience) should have a progress indicator. So, when a student completes everything to get credit for that requirement it should be indicated. 
If there is no experience then it should be an empty input box, if there is something in a summer experience the text box should be populated with it. 
Add a place to allow students to indicate they are interested in the Minor
Add a place that shows a student's current minor status. If a student has done nothing in the minor we show nothing, “Interested” if they have indicated interest, and “In Progress” if they have credit for any minor requirement. 
A text blurb that says something like: “Click here for more information on the Community and Civic Engagement minor.”. The here is a hyperlink to the Berea catalog page for the minor. (https://berea.smartcatalogiq.com/en/current/catalog/departments-of-study/interdisciplinary-minor/community-and-civic-engagement-minor/) 
 
## Sustained engagement section:
- Section title should be: “Sustained Community Engagement” 
- Get all terms that student has event participation or SLC participation records  
- Get all the community engagement activities that the student has been credited.
- Limit activities that can credit towards the term to 2 in a single term. 
- Give a short text blurb about sustained engagement requirements under the header. Example: 
- “Approximately two hours of engagement over about ten weeks of a semester. Only two engagement activities can be credited in a single semester. “

## Summer Experience section:
- Section title should be: “Community-Engaged Summer Experience” 
- Give a short text blurb about the summer experience requirements under the header. Example: 
- “Must include at least 300 hours of work over the span of 8 weeks with a public-facing organization with a focus on applied work.”

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Minor UI for students #989](https://trello.com/c/86jeLGH4/655-add-minor-ui-for-students-989)

**Comment by bledsoef** [comment]
Closed in PR #1096
