### ISSUE TITLE
CELTS Position information added to the `Program Manager` accordion

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#991]
The `Program Manager` accordion should also include a "CELTS position". The position should be selectable by admins. We need to record a record every time the "CELTS position" changes so that we know when the new position started and the old position ended, we do not want to overwrite the records of their old position. 

In the service transcript, show the progress through positions during their time at CELTS. We need to think about a good database representation and presentation logic to allow us to put something like "CELTS Associate: Fall 2022 - Spring 2025" in the service transcript.

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Extend functionality of the Program Manager accordion #991](https://trello.com/c/TMKjPwUc/657-extend-functionality-of-the-program-manager-accordion-991)

**Comment by bledsoef** [comment]
Is this resolved or currently being worked on?
