### ISSUE TITLE
Show relative dates for events

### ISSUE THREAD

**Issue by AndersonStettner** [BCStudentSoftwareDevTeam/celts#998]
We should add a relative date to the Event View. Something like: 
"Event is today at __" 
"Event is in _ days" 
"Event is this Saturday"

**Comment by AndersonStettner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Show relative dates for events #998](https://trello.com/c/gs7p4Rlw/663-show-relative-dates-for-events-998)

**Comment by doucoureb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Show relative dates for events #998](https://trello.com/c/gs7p4Rlw/663-show-relative-dates-for-events-998)

**Comment by bledsoef** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Countdown on Event View](https://trello.com/c/CruRR9HM/753-countdown-on-event-view)
